CREATE OR REPLACE FUNCTION pontis.f_Structuretype(v_Brkey      Userstrunit.Brkey%TYPE,
                                           v_Strunitkey Userstrunit.Strunitkey%TYPE)
  RETURN VARCHAR2 IS
  Retval VARCHAR2(4);
BEGIN

  SELECT Decode(Us.Unit_Material,
                1,
                'S',
                2,
                'W',
                3,
                'C',
                4,
                'I',
                5,
                'A',
                6,
                'R',
                7,
                'P',
                8,
                'L',
                9,
                'M',
                10,
                'T',
                11,
                'X',
                12,
                'Y',
                13,
                'F') || Decode(Us.Unit_Type,
                               1,
                               'AR',
                               2,
                               'OA',
                               3,
                               'FA',
                               4,
                               'TA',
                               11,
                               'CB',
                               12,
                               'FB',
                               21,
                               'RF',
                               22,
                               'GC',
                               31,
                               'DG',
                               32,
                               'TG',
                               33,
                               'BG',
                               34,
                               'FG',
                               35,
                               'SG',
                               36,
                               'RG',
                               37,
                               'WG',
                               38,
                               'BM',
                               41,
                               'MP',
                               42,
                               'SP',
                               43,
                               'LP',
                               51,
                               'CS',
                               52,
                               'IS',
                               53,
                               'VS',
                               61,
                               'DT',
                               62,
                               'HT',
                               63,
                               'LT',
                               71,
                               'TU',
                               72,
                               'LW',
                               73,
                               'SS',
                               83,
                               'BC',
                               84,
                               'FC',
                               85,
                               'SC',
                               86,
                               'RC',
                               87,
                               'WC',
                               88,
                               'MC',
                               89,
                               'IT') ||
         Decode(Us.Super_Design_Ty,
                0,
                '',
                1,
                'S',
                2,
                'C',
                3,
                'H',
                4,
                'P',
                5,
                'F',
                6,
                'T',
                7,
                'D',
                8,
                'L',
                9,
                'R')
    INTO Retval
    FROM Userstrunit Us
   WHERE Us.Brkey = v_Brkey
     AND Us.Strunitkey = v_Strunitkey;

  RETURN Retval;
EXCEPTION
  WHEN No_Data_Found THEN
    RETURN - 1;
  WHEN OTHERS THEN
    RAISE;
END f_Structuretype;
/