CREATE MATERIALIZED VIEW pontis.mv_jurisdiction_rpt_sum (col_name,sortorder,grporder,nbi_2006,nbi_2007,nbi_2008,nbi_2009,nbi_2010,nbi_2011,nbi_2012,nbi_2013,nbi_2014,nbi_2015,last_percent_tot,percent_tot)
REFRESH START WITH TO_DATE('2016-5-18 15:12:24', 'yyyy-mm-dd hh24:mi:ss') NEXT SYSDATE + 6/24 
AS select 'Total Bridges' col_name,
        1 sortorder,
        1 grporder,
        count(case when juris = 'State' and inspec_year = '2006' and trim(SDFO) is not null then 1 else null end) nbi_2006,
        count(case when juris = 'State' and inspec_year = '2007' and trim(SDFO) is not null then 1 else null end) nbi_2007,
        count(case when juris = 'State' and inspec_year = '2008' and trim(SDFO) is not null then 1 else null end) nbi_2008,
        count(case when juris = 'State' and inspec_year = '2009' and trim(SDFO) is not null then 1 else null end) nbi_2009,
        count(case when juris = 'State' and inspec_year = '2010' and trim(SDFO) is not null then 1 else null end) nbi_2010,
        count(case when juris = 'State' and inspec_year = '2011' and trim(SDFO) is not null then 1 else null end) nbi_2011,
        count(case when juris = 'State' and inspec_year = '2012' and trim(SDFO) is not null then 1 else null end) nbi_2012,
        count(case when juris = 'State' and inspec_year = '2013' and trim(SDFO) is not null then 1 else null end) nbi_2013,
        count(case when juris = 'State' and inspec_year = '2014' and trim(SDFO) is not null then 1 else null end) nbi_2014,
        count(case when juris = 'State' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end) nbi_2015,
        count(case when juris = 'State' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end) last_percent_tot,
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end) percent_tot
from mv_jurisdiction_rpt
UNION ALL
select 'Structurally Deficient',
        2,
        1,
        count(case when juris = 'State' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Functionally Obsolete',
        3,
        1,
        count(case when juris = 'State' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Non-Deficient',
        4,
        1,
        count(case when juris = 'State' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'State' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Total Bridges',
        1,
        2,
        count(case when juris = 'City' and inspec_year = '2006' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2007' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2008' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2009' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2010' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2011' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2012' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2013' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2014' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Structurally Deficient',
        2,
        2,
        count(case when juris = 'City' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Functionally Obsolete',
        3,
        2,
        count(case when juris = 'City' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '2'then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Non-Deficient',
        4,
        2,
        count(case when juris = 'City' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'City' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Total Bridges',
        1,
        3,
        count(case when juris = 'County' and inspec_year = '2006' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2007' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2008' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2009' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2010' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2011' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2012' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2013' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2014' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Structurally Deficient',
        2,
        3,
        count(case when juris = 'County' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Functionally Obsolete',
        3,
        3,
        count(case when juris = 'County' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Non-Deficient',
        4,
        3,
        count(case when juris = 'County' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'County' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
union all
select 'Total Bridges',
        1,
        4,
        count(case when juris = 'KTA' and inspec_year = '2006' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2007' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2008' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2009' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2010' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2011' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2012' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2013' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2014' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Structurally Deficient',
        2,
        4,
        count(case when juris = 'KTA' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Functionally Obsolete',
        3,
        4,
        count(case when juris = 'KTA' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Non-Deficient',
        4,
        4,
        count(case when juris = 'KTA' and inspec_year = '2006' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2007' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2008' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2009' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2010' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2011' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2012' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2013' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2014' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2015' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when juris = 'KTA' and inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Total Bridges',
        1,
        5,
        count(case when inspec_year = '2006' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2007' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2008' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2009' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2010' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2011' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2012' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2013' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2014' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Structurally Deficient',
        2,
        5,
        count(case when inspec_year = '2006' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2007' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2008' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2009' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2010' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2011' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2012' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2013' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2014' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2015' and nvl(trim(sdfo),-1) = '1' then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Functionally Obsolete',
        3,
        5,
        count(case when  inspec_year = '2006' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2007' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2008' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2009' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2010' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2011' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2012' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2013' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2014' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2015' and nvl(trim(sdfo),-1) = '2' then 1 else null end),
        count(case when  inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when  inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select 'Non-Deficient',
        4,
        5,
        count(case when  inspec_year = '2006' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2007' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2008' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2009' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2010' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2011' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2012' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2013' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2014' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2015' and nvl(trim(sdfo),-1) = '0' then 1 else null end),
        count(case when  inspec_year = '2015' and trim(SDFO) is not null then 1 else null end),
        count(case when  inspec_year = '2015' and trim(SDFO) is not null then 1 else null end)
from mv_jurisdiction_rpt
UNION ALL
select '0 to 49.9',
       1,
       6,
       count(case when inspec_year = '2006' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2007' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2008' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2009' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2010' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2011' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2012' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2013' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2014' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and suffgroup = 1 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
-1
from mv_jurisdiction_rpt
union all
select '50 to 80',
       2,
       6,
       count(case when inspec_year = '2006' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2007' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2008' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2009' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2010' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2011' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2012' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2013' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2014' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and suffgroup = 2 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
-1
from mv_jurisdiction_rpt
union all
select '80 to 100',
       3,
       6,
       count(case when inspec_year = '2006' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2007' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2008' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2009' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2010' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2011' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2012' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2013' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2014' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and suffgroup = 3 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
-1
from mv_jurisdiction_rpt
union all
select 'Total Rated Bridges',
       4,
       6,
       count(case when inspec_year = '2006' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2007' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2008' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2009' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2010' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2011' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2012' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2013' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2014' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and suffgroup <> 0 and juris in ('KTA','State') then 1 else null end),
-1
from mv_jurisdiction_rpt
union all
select 'Temp Cribbed Bridges(State)',
       1,
       7,
       count(case when inspec_year = '2006' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2007' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2008' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2009' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2010' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2011' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2012' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2013' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2014' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and NBI_103 = 'T' and juris in ('KTA','State') then 1 else null end),
-1,
-1
from mv_jurisdiction_rpt
union all
select 'Posted Bridges(State)',
       2,
       7,
       count(case when inspec_year = '2006' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2007' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2008' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2009' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2010' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2011' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2012' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2013' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2014' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
       count(case when inspec_year = '2015' and posted = 'Y' and juris in ('KTA','State') then 1 else null end),
-1,
-1
from mv_jurisdiction_rpt;