CREATE TABLE pontis.health_index_raw (
  brkey VARCHAR2(15 BYTE),
  inspdate DATE,
  inspkey VARCHAR2(4 BYTE),
  strunitkey NUMBER(4),
  strunittype CHAR,
  strtype VARCHAR2(4 BYTE),
  elemkey NUMBER,
  envkey NUMBER,
  ecatkey NUMBER,
  matlkey NUMBER,
  etypkey VARCHAR2(2 BYTE),
  grpcatkey NUMBER,
  unitvalue FLOAT,
  tev FLOAT,
  cev FLOAT,
  elem_hi FLOAT,
  elem_hi_adj FLOAT,
  adj_cev FLOAT,
  dk_flag FLOAT,
  sup_flag FLOAT,
  culv_flag FLOAT,
  brdgculv CHAR
);