CREATE TABLE pontis.kaws_inspevnt_temp_2 (
  inspecfirm VARCHAR2(4000 BYTE),
  serialnumber VARCHAR2(15 BYTE),
  co_ser VARCHAR2(15 BYTE) NOT NULL,
  inspkey VARCHAR2(4 BYTE) NOT NULL,
  intrvl FLOAT,
  inspdate DATE,
  rating NUMBER(1),
  healthindex NUMBER(16,1),
  recom_contr_maint VARCHAR2(2000 BYTE),
  recom_dist_maint VARCHAR2(2000 BYTE),
  recom_area_maint VARCHAR2(2000 BYTE),
  qcqa_flag CHAR,
  inspname1 VARCHAR2(24 BYTE),
  inspname2 VARCHAR2(24 BYTE),
  inspfirm VARCHAR2(24 BYTE),
  traffic_cntrl CHAR,
  traffic_cntrl_comments VARCHAR2(400 BYTE),
  anchorboltlength_measured FLOAT,
  inspec_notes VARCHAR2(2000 BYTE),
  crtcl_find_date DATE,
  crtcl_find_compl DATE,
  crtcl_comments VARCHAR2(2000 BYTE),
  crtcl_element NUMBER(3)
);