CREATE TABLE pontis.ktareport (
  brkey VARCHAR2(6 BYTE),
  brg_name VARCHAR2(10 BYTE),
  func VARCHAR2(50 BYTE),
  ftcr VARCHAR2(50 BYTE),
  route VARCHAR2(15 BYTE),
  insp_date DATE,
  deck VARCHAR2(2 BYTE),
  super VARCHAR2(2 BYTE),
  sub VARCHAR2(2 BYTE),
  channel VARCHAR2(2 BYTE),
  culv VARCHAR2(2 BYTE),
  strc VARCHAR2(2 BYTE),
  dgeo VARCHAR2(2 BYTE),
  uncl VARCHAR2(2 BYTE),
  watr VARCHAR2(2 BYTE),
  algn VARCHAR2(2 BYTE),
  fclastdate DATE,
  uwlastdate DATE,
  bridgeno VARCHAR2(10 BYTE),
  northsouth VARCHAR2(50 BYTE),
  "IDENTIFIER" NUMBER(2),
  CONSTRAINT fk_brkey FOREIGN KEY (brkey) REFERENCES pontis.bridge (brkey) ON DELETE CASCADE DISABLE NOVALIDATE
);