CREATE TABLE pontis.load_ratings_upl_newbr (
  brkey VARCHAR2(8 BYTE) NOT NULL,
  irload_wsd_h FLOAT,
  orload_wsd_h FLOAT,
  irload_lfd_h FLOAT,
  orload_lfd_h FLOAT,
  irload_wsd_3 FLOAT,
  orload_wsd_3 FLOAT,
  irload_lfd_3 FLOAT,
  orload_lfd_3 FLOAT,
  irload_wsd_hs FLOAT,
  orload_wsd_hs FLOAT,
  irload_lfd_hs FLOAT,
  orload_lfd_hs FLOAT,
  irload_wsd_3s2 FLOAT,
  orload_wsd_3s2 FLOAT,
  irload_lfd_3s2 FLOAT,
  orload_lfd_3s2 FLOAT,
  irload_wsd_3_3 FLOAT,
  orload_wsd_3_3 FLOAT,
  irload_lfd_3_3 FLOAT,
  orload_lfd_3_3 FLOAT,
  irload_wsd_t130 FLOAT,
  orload_wsd_t130 FLOAT,
  irload_lfd_t130 FLOAT,
  orload_lfd_t130 FLOAT,
  irload_wsd_t170 FLOAT,
  orload_wsd_t170 FLOAT,
  irload_lfd_t170 FLOAT,
  orload_lfd_t170 FLOAT,
  ratingdate DATE,
  rating_comment CHAR,
  rater_initials VARCHAR2(3 BYTE),
  irload_hl93 FLOAT,
  orload_hl93 FLOAT,
  CONSTRAINT pk_load_ratings_upl_newbr PRIMARY KEY (brkey)
);