CREATE TABLE pontis.netmetric (
  sckey VARCHAR2(2 BYTE) NOT NULL,
  dim1val VARCHAR2(2 BYTE) NOT NULL,
  dim2val VARCHAR2(2 BYTE) NOT NULL,
  dim3val VARCHAR2(2 BYTE) NOT NULL,
  dim4val VARCHAR2(2 BYTE) NOT NULL,
  ykey NUMBER(4) NOT NULL,
  struccount NUMBER(6),
  adtc_1 NUMBER(6),
  adtc_2 NUMBER(6),
  adtc_3 NUMBER(6),
  adtc_4 NUMBER(6),
  adtc_5 NUMBER(6),
  healthindex NUMBER(5,1),
  hix_1 NUMBER(6),
  hix_2 NUMBER(6),
  hix_3 NUMBER(6),
  hix_4 NUMBER(6),
  paintindex NUMBER(5,1),
  hix_super NUMBER(5,1),
  hix_sub NUMBER(5,1),
  hix_joints NUMBER(5,1),
  hix_bearings NUMBER(5,1),
  hix_decks NUMBER(5,1),
  hix_other NUMBER(5,1),
  rdeck_0 NUMBER(6),
  rdeck_1 NUMBER(6),
  rdeck_2 NUMBER(6),
  rdeck_3 NUMBER(6),
  rdeck_4 NUMBER(6),
  rdeck_5 NUMBER(6),
  rdeck_6 NUMBER(6),
  rdeck_7 NUMBER(6),
  rdeck_8 NUMBER(6),
  rdeck_9 NUMBER(6),
  rdeck_n NUMBER(6),
  rsuper_0 NUMBER(6),
  rsuper_1 NUMBER(6),
  rsuper_2 NUMBER(6),
  rsuper_3 NUMBER(6),
  rsuper_4 NUMBER(6),
  rsuper_5 NUMBER(6),
  rsuper_6 NUMBER(6),
  rsuper_7 NUMBER(6),
  rsuper_8 NUMBER(6),
  rsuper_9 NUMBER(6),
  rsuper_n NUMBER(6),
  rsub_0 NUMBER(6),
  rsub_1 NUMBER(6),
  rsub_2 NUMBER(6),
  rsub_3 NUMBER(6),
  rsub_4 NUMBER(6),
  rsub_5 NUMBER(6),
  rsub_6 NUMBER(6),
  rsub_7 NUMBER(6),
  rsub_8 NUMBER(6),
  rsub_9 NUMBER(6),
  rsub_n NUMBER(6),
  rculv_0 NUMBER(6),
  rculv_1 NUMBER(6),
  rculv_2 NUMBER(6),
  rculv_3 NUMBER(6),
  rculv_4 NUMBER(6),
  rculv_5 NUMBER(6),
  rculv_6 NUMBER(6),
  rculv_7 NUMBER(6),
  rculv_8 NUMBER(6),
  rculv_9 NUMBER(6),
  rculv_n NUMBER(6),
  rstr_0 NUMBER(6),
  rstr_1 NUMBER(6),
  rstr_2 NUMBER(6),
  rstr_3 NUMBER(6),
  rstr_4 NUMBER(6),
  rstr_5 NUMBER(6),
  rstr_6 NUMBER(6),
  rstr_7 NUMBER(6),
  rstr_8 NUMBER(6),
  rstr_9 NUMBER(6),
  rstr_n NUMBER(6),
  rdeckgeom_0 NUMBER(6),
  rdeckgeom_1 NUMBER(6),
  rdeckgeom_2 NUMBER(6),
  rdeckgeom_3 NUMBER(6),
  rdeckgeom_4 NUMBER(6),
  rdeckgeom_5 NUMBER(6),
  rdeckgeom_6 NUMBER(6),
  rdeckgeom_7 NUMBER(6),
  rdeckgeom_8 NUMBER(6),
  rdeckgeom_9 NUMBER(6),
  rdeckgeom_n NUMBER(6),
  runderclr_0 NUMBER(6),
  runderclr_1 NUMBER(6),
  runderclr_2 NUMBER(6),
  runderclr_3 NUMBER(6),
  runderclr_4 NUMBER(6),
  runderclr_5 NUMBER(6),
  runderclr_6 NUMBER(6),
  runderclr_7 NUMBER(6),
  runderclr_8 NUMBER(6),
  runderclr_9 NUMBER(6),
  runderclr_n NUMBER(6),
  suffrating_1 NUMBER(6),
  suffrating_2 NUMBER(6),
  suffrating_3 NUMBER(6),
  suffrating_4 NUMBER(6),
  nbirating_0 NUMBER(6),
  nbirating_1 NUMBER(6),
  nbirating_2 NUMBER(6),
  nbirating_n NUMBER(6),
  elig_repl NUMBER(6),
  elig_rehab NUMBER(6),
  elig_not NUMBER(6),
  elig_repl_area FLOAT,
  elig_rehab_area FLOAT,
  elig_not_area FLOAT,
  needs NUMBER(10),
  progwork NUMBER(10),
  benneeds NUMBER(10),
  benwork NUMBER(10),
  strucneed NUMBER(6),
  strucdone NUMBER(6),
  CONSTRAINT netmetric_pk PRIMARY KEY (sckey,dim1val,dim2val,dim3val,dim4val,ykey),
  CONSTRAINT fk_netmetri_79_scenario FOREIGN KEY (sckey) REFERENCES pontis.scenario (sckey) ON DELETE CASCADE
);
COMMENT ON COLUMN pontis.netmetric.sckey IS 'Scenario key';
COMMENT ON COLUMN pontis.netmetric.dim1val IS 'First policy dimension selection value';
COMMENT ON COLUMN pontis.netmetric.dim2val IS 'Second policy dimension selection value';
COMMENT ON COLUMN pontis.netmetric.dim3val IS 'Third policy--cost dimension selection value';
COMMENT ON COLUMN pontis.netmetric.dim4val IS 'Fourth policy--cost dimension selection value';
COMMENT ON COLUMN pontis.netmetric.hix_1 IS 'Health Index Cohort 1 Count';
COMMENT ON COLUMN pontis.netmetric.hix_2 IS 'Health Index Cohort 2 Count';
COMMENT ON COLUMN pontis.netmetric.hix_3 IS 'Health Index Cohort 3 Count';
COMMENT ON COLUMN pontis.netmetric.hix_4 IS 'Health Index Cohort 4 Count';
COMMENT ON COLUMN pontis.netmetric.elig_repl IS 'Number of structures eligible for HBRR funds for replacement';
COMMENT ON COLUMN pontis.netmetric.elig_rehab IS 'Number of structures eligible for HBRR funds for rehabilitation';
COMMENT ON COLUMN pontis.netmetric.elig_not IS 'Number of structures not eligible for HBRR funds';
COMMENT ON COLUMN pontis.netmetric.elig_repl_area IS 'Deck area (m2) of the bridges that are eligible for HBRR funds for replacement';
COMMENT ON COLUMN pontis.netmetric.elig_rehab_area IS 'Deck area (m2) of the bridges that are eligible for HBRR funds for rehabilitation';
COMMENT ON COLUMN pontis.netmetric.elig_not_area IS 'Deck area (m2) of the bridges that are not eligible for HBRR funds';