CREATE TABLE pontis.pon_app_users (
  userkey NUMBER(38) NOT NULL,
  userid VARCHAR2(128 BYTE) NOT NULL,
  last_name VARCHAR2(64 BYTE) NOT NULL,
  first_name VARCHAR2(64 BYTE) NOT NULL,
  status NUMBER(38) DEFAULT 1 NOT NULL,
  agency VARCHAR2(64 BYTE),
  phone VARCHAR2(32 BYTE),
  email VARCHAR2(128 BYTE),
  createdatetime DATE,
  createuserkey NUMBER(38),
  modtime DATE,
  moduserkey NUMBER(38),
  "PASSWORD" VARCHAR2(128 BYTE),
  middle_name VARCHAR2(64 BYTE),
  district VARCHAR2(64 BYTE),
  title VARCHAR2(64 BYTE),
  address1 VARCHAR2(128 BYTE),
  address2 VARCHAR2(128 BYTE),
  city VARCHAR2(64 BYTE),
  "STATE" VARCHAR2(64 BYTE),
  zip VARCHAR2(16 BYTE),
  fax VARCHAR2(16 BYTE),
  initials VARCHAR2(8 BYTE),
  is_disabled NUMBER(38) DEFAULT 0,
  CONSTRAINT pon_app_users_pk PRIMARY KEY (userkey) DISABLE NOVALIDATE
);