CREATE TABLE pontis.pon_insp_workcand (
  iwc_workcand_id VARCHAR2(30 BYTE) NOT NULL,
  brkey VARCHAR2(15 BYTE) NOT NULL,
  inspkey VARCHAR2(4 BYTE) NOT NULL,
  strunitkey NUMBER(4),
  flex_action_key VARCHAR2(8 BYTE),
  iwc_agency_priority VARCHAR2(4 BYTE),
  iwc_work_rec_date DATE DEFAULT SYSDATE,
  iwc_target_year NUMBER(4),
  iwc_work_assigned VARCHAR2(4 BYTE),
  iwc_assigned VARCHAR2(4 BYTE),
  iwc_est_cost NUMBER(10),
  iwc_est_qty FLOAT,
  iwc_status VARCHAR2(4 BYTE),
  iwc_createdatetime DATE DEFAULT SYSDATE,
  iwc_createuserkey VARCHAR2(38 BYTE),
  iwc_modtime DATE DEFAULT SYSDATE,
  iwc_moduserkey VARCHAR2(38 BYTE),
  iwc_docrefkey VARCHAR2(255 BYTE),
  iwc_notes VARCHAR2(2000 BYTE),
  iwc_workcomp_date DATE,
  iwc_cost_per_unit NUMBER(10),
  iwc_workcand_name VARCHAR2(30 BYTE),
  CONSTRAINT pon_insp_workcand_pk PRIMARY KEY (iwc_workcand_id),
  CONSTRAINT fk_pon_insp_workcand_flex FOREIGN KEY (flex_action_key) REFERENCES pontis.pon_flexactions_sets (flex_action_key),
  CONSTRAINT fk_pon_insp_workcand_inspevnt FOREIGN KEY (brkey,inspkey) REFERENCES pontis.inspevnt (brkey,inspkey)
);