CREATE TABLE pontis.pon_nav_control (
  tab_id NUMBER(38) NOT NULL,
  task_id NUMBER(38) NOT NULL,
  control_group_id NUMBER(38) NOT NULL,
  control_id NUMBER(38) NOT NULL,
  "NAME" VARCHAR2(32 BYTE) NOT NULL,
  label_caption_id NUMBER(38) NOT NULL,
  order_num NUMBER(38) NOT NULL,
  visible_ind CHAR NOT NULL,
  read_only_ind CHAR NOT NULL,
  table_name VARCHAR2(30 BYTE),
  column_name VARCHAR2(30 BYTE),
  control_type VARCHAR2(32 BYTE),
  height VARCHAR2(16 BYTE),
  field_width VARCHAR2(16 BYTE),
  label_width VARCHAR2(16 BYTE),
  value_color VARCHAR2(32 BYTE),
  value_bold_ind CHAR,
  label_color VARCHAR2(32 BYTE),
  label_bold_ind CHAR,
  show_unit_ind CHAR,
  skin_id VARCHAR2(64 BYTE),
  css_class VARCHAR2(64 BYTE),
  auto_postback_ind CHAR,
  postback_event_id VARCHAR2(64 BYTE),
  causes_validation_ind CHAR,
  missing_as_blank_ind CHAR,
  regex_error_message VARCHAR2(128 BYTE),
  required_field_error_message VARCHAR2(128 BYTE),
  range_error_message VARCHAR2(128 BYTE),
  range_minimum NUMBER(38),
  range_maximum NUMBER(38),
  validate_range_ind CHAR,
  validate_regex_ind CHAR,
  validate_required_field_ind CHAR,
  default_value_display VARCHAR2(64 BYTE),
  text_box_mode VARCHAR2(32 BYTE),
  tab_index NUMBER(38),
  horizontal_alignment VARCHAR2(32 BYTE),
  vertical_alignment VARCHAR2(32 BYTE),
  cell_padding NUMBER(38),
  cell_spacing NUMBER(38),
  wrap_text_ind CHAR,
  image_url VARCHAR2(256 BYTE),
  max_chars NUMBER(38),
  enable_view_state_ind CHAR,
  ddx_type_id VARCHAR2(64 BYTE),
  desktop_url VARCHAR2(256 BYTE),
  multi_line_rows NUMBER(38),
  tooltip_caption_id NUMBER(38),
  control_gui_resource_id VARCHAR2(256 BYTE),
  image_alignment VARCHAR2(32 BYTE),
  text_alignment VARCHAR2(32 BYTE),
  on_client_click VARCHAR2(256 BYTE),
  popup_task_id NUMBER(38),
  pontis_standard_ind CHAR,
  override_param_table_name VARCHAR2(30 BYTE),
  override_param_field_name VARCHAR2(30 BYTE),
  link_key NUMBER(4),
  CONSTRAINT pon_nav_control_pk PRIMARY KEY (tab_id,task_id,control_group_id,control_id) DISABLE NOVALIDATE,
  CONSTRAINT fk_nav_ctrl_to_caption FOREIGN KEY (label_caption_id) REFERENCES pontis.pon_app_caption (caption_id) DISABLE NOVALIDATE,
  CONSTRAINT fk_nav_ctrl_to_caption_two FOREIGN KEY (tooltip_caption_id) REFERENCES pontis.pon_app_caption (caption_id) DISABLE NOVALIDATE,
  CONSTRAINT fk_nav_ctrl_to_ctrlgrp FOREIGN KEY (tab_id,task_id,control_group_id) REFERENCES pontis.pon_nav_control_group (tab_id,task_id,control_group_id) DISABLE NOVALIDATE,
  CONSTRAINT fk_nav_ctrl_to_task FOREIGN KEY (tab_id,popup_task_id) REFERENCES pontis.pon_nav_task (tab_id,task_id) DISABLE NOVALIDATE
);