CREATE TABLE pontis.tbl_history_bridges (
  co_ser VARCHAR2(10 BYTE),
  strtype VARCHAR2(4 BYTE),
  year_built DATE,
  year_removed DATE,
  dk_rating CHAR,
  sup_rating CHAR,
  sub_rating CHAR,
  chan_rating CHAR,
  culv_rating CHAR,
  str_rating CHAR,
  deck_geom CHAR,
  undr_rating CHAR,
  water_adeq CHAR,
  appr_rating CHAR,
  last_insp DATE,
  deck_hi FLOAT,
  sup_hi FLOAT,
  sub_hi FLOAT,
  culv_hi FLOAT,
  suff_rate FLOAT,
  sdfo CHAR,
  future_average_daily_traffic FLOAT,
  pct_trucks FLOAT,
  orload_wsd_hs FLOAT,
  orload_lfd_hs FLOAT,
  orload_adj_hs FLOAT,
  irload_wsd_hs FLOAT,
  irload_lfd_hs FLOAT,
  irload_adj_hs FLOAT
);