CREATE TABLE pontis.temp_305 (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  inspkey VARCHAR2(4 BYTE) NOT NULL,
  elem_key CHAR(3 BYTE),
  elem_parent_key CHAR,
  envkey NUMBER(1) NOT NULL,
  strunitkey NUMBER(4) NOT NULL,
  elem_grandparent_key CHAR,
  elem_quantity FLOAT NOT NULL,
  elem_pctstate1 FLOAT NOT NULL,
  elem_pctstate2 FLOAT NOT NULL,
  elem_pctstate3 FLOAT NOT NULL,
  elem_pctstate4 FLOAT NOT NULL,
  elem_qtystate1 FLOAT NOT NULL,
  elem_qtystate2 FLOAT NOT NULL,
  elem_qtystate3 FLOAT NOT NULL,
  elem_qtystate4 FLOAT NOT NULL,
  elem_scale_factor FLOAT,
  elem_desc VARCHAR2(255 BYTE),
  elem_createdatetime DATE,
  elem_createuserkey CHAR,
  elem_modtime DATE,
  elem_mod_userkey CHAR,
  elem_docrefkey CHAR,
  elem_notes CHAR
);