CREATE TABLE pontis.userstrunit (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  strunitkey NUMBER(4) NOT NULL,
  unit_material VARCHAR2(4 BYTE),
  unit_type VARCHAR2(4 BYTE),
  super_design_ty VARCHAR2(2 BYTE),
  num_girders NUMBER,
  wide_material VARCHAR2(4 BYTE),
  wide_type VARCHAR2(4 BYTE),
  wide_design_ty VARCHAR2(2 BYTE),
  wide_num_girders NUMBER,
  abut_foot_near VARCHAR2(4 BYTE),
  abut_type_near VARCHAR2(4 BYTE),
  abut_foot_far VARCHAR2(4 BYTE),
  abut_type_far VARCHAR2(4 BYTE),
  bearing_type VARCHAR2(4 BYTE),
  rail_type VARCHAR2(4 BYTE),
  crit_note_cul_1 VARCHAR2(4 BYTE),
  crit_note_cul_2 VARCHAR2(4 BYTE),
  crit_note_dk_1 VARCHAR2(4 BYTE),
  crit_note_dk_2 VARCHAR2(4 BYTE),
  dk_drain_sys VARCHAR2(4 BYTE),
  deck_matrl VARCHAR2(4 BYTE),
  deckseal VARCHAR2(4 BYTE),
  dkprotect CHAR,
  dkmembtype CHAR,
  dksurftype VARCHAR2(2 BYTE),
  deck_thick FLOAT,
  wear_thick FLOAT,
  expan_dev_far VARCHAR2(4 BYTE),
  expan_dev_near VARCHAR2(4 BYTE),
  exp_dev_mfr_far VARCHAR2(25 BYTE),
  exp_dev_mfr_nr VARCHAR2(25 BYTE),
  hinge_type VARCHAR2(4 BYTE),
  "LENGTH" FLOAT,
  len_span_grp_1 FLOAT,
  len_span_grp_2 FLOAT,
  len_span_grp_3 FLOAT,
  len_span_grp_4 FLOAT,
  len_span_grp_5 FLOAT,
  len_span_grp_6 FLOAT,
  len_span_grp_7 FLOAT,
  len_span_grp_8 FLOAT,
  len_span_grp_9 FLOAT,
  len_span_grp_10 FLOAT,
  tot_num_spans NUMBER,
  num_spans_grp_1 NUMBER,
  num_spans_grp_2 NUMBER,
  num_spans_grp_3 NUMBER,
  num_spans_grp_4 NUMBER,
  num_spans_grp_5 NUMBER,
  num_spans_grp_6 NUMBER,
  num_spans_grp_7 NUMBER,
  num_spans_grp_8 NUMBER,
  num_spans_grp_9 NUMBER,
  num_spans_grp_10 NUMBER,
  pier_foot_type VARCHAR2(4 BYTE),
  pier_type VARCHAR2(4 BYTE),
  crit_note_sub_1 VARCHAR2(4 BYTE),
  crit_note_sub_2 VARCHAR2(4 BYTE),
  crit_note_sup_1 VARCHAR2(4 BYTE),
  crit_note_sup_2 VARCHAR2(4 BYTE),
  crit_note_sup_3 VARCHAR2(4 BYTE),
  crit_note_sup_4 VARCHAR2(4 BYTE),
  crit_note_sup_5 VARCHAR2(4 BYTE),
  dk_top_delams NUMBER,
  dk_top_spalls NUMBER,
  dk_top_deter NUMBER,
  dk_deter_btm NUMBER,
  dk_spalls_btm NUMBER,
  unit_dk_rating CHAR,
  unit_sup_rating CHAR,
  unit_sub_rating CHAR,
  unit_culv_rating CHAR,
  createdatetime DATE,
  createuserkey VARCHAR2(4 BYTE),
  modtime DATE,
  userkey VARCHAR2(4 BYTE),
  notes VARCHAR2(2000 BYTE),
  CONSTRAINT userstrunit_pk PRIMARY KEY (brkey,strunitkey),
  CONSTRAINT fk_userstru_103_structur FOREIGN KEY (brkey,strunitkey) REFERENCES pontis.structure_unit (brkey,strunitkey) ON DELETE CASCADE
);