CREATE TABLE pontis.userinsp_temp (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  inspkey VARCHAR2(4 BYTE) NOT NULL,
  r_inspname_1 VARCHAR2(4 BYTE),
  r_inspname_2 VARCHAR2(4 BYTE),
  f_inspname_1 VARCHAR2(4 BYTE),
  f_inspname_2 VARCHAR2(4 BYTE),
  uw_inspname_1 VARCHAR2(4 BYTE),
  uw_inspname_2 VARCHAR2(4 BYTE),
  os_inspname_1 VARCHAR2(4 BYTE),
  os_inspname_2 VARCHAR2(4 BYTE),
  snoop_type CHAR(2 BYTE),
  snoop_insp_done CHAR,
  snoop_insp_req CHAR,
  uwater_insp_typ CHAR,
  os_insp_type VARCHAR2(2 BYTE),
  crtcl_find_date DATE,
  crtcl_find_comp DATE,
  crtcl_comments VARCHAR2(2000 BYTE),
  scour_find_date DATE,
  scour_find_comp DATE,
  scour_comments VARCHAR2(2000 BYTE),
  createdatetime DATE,
  createuserkey VARCHAR2(4 BYTE),
  modtime DATE,
  userkey VARCHAR2(4 BYTE),
  notes VARCHAR2(2000 BYTE)
);