CREATE TABLE pontis.v_eleminsp (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  inspkey VARCHAR2(4 BYTE) NOT NULL,
  elemkey NUMBER(3) NOT NULL,
  envkey NUMBER(1) NOT NULL,
  strunitkey NUMBER(4) NOT NULL,
  elmrowidkey VARCHAR2(30 BYTE),
  elinspdate DATE,
  quantity FLOAT NOT NULL,
  elem_scale_factor FLOAT,
  pctstate1 FLOAT NOT NULL,
  qtystate1 FLOAT,
  pctstate2 FLOAT NOT NULL,
  qtystate2 FLOAT,
  pctstate3 FLOAT NOT NULL,
  qtystate3 FLOAT,
  pctstate4 FLOAT NOT NULL,
  qtystate4 FLOAT,
  pctstate5 FLOAT NOT NULL,
  qtystate5 FLOAT,
  elcondest CHAR,
  citrigger CHAR,
  description VARCHAR2(255 BYTE),
  createdatetime DATE,
  createuserkey VARCHAR2(4 BYTE),
  modtime DATE,
  userkey VARCHAR2(4 BYTE),
  docrefkey VARCHAR2(255 BYTE),
  notes VARCHAR2(2000 BYTE)
);