CREATE TABLE pontis.vc_bridge (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  bridge_id VARCHAR2(30 BYTE) NOT NULL,
  struct_num VARCHAR2(15 BYTE),
  strucname VARCHAR2(50 BYTE),
  featint VARCHAR2(24 BYTE),
  fhwa_regn CHAR,
  district VARCHAR2(2 BYTE),
  county VARCHAR2(3 BYTE),
  "FACILITY" VARCHAR2(18 BYTE),
  "LOCATION" VARCHAR2(25 BYTE),
  custodian VARCHAR2(2 BYTE),
  "OWNER" VARCHAR2(2 BYTE),
  adminarea VARCHAR2(2 BYTE),
  bridgegroup VARCHAR2(20 BYTE),
  nstatecode VARCHAR2(3 BYTE),
  n_fhwa_reg CHAR,
  bb_pct NUMBER(2),
  bb_brdgeid VARCHAR2(15 BYTE),
  propwork VARCHAR2(2 BYTE),
  workby CHAR,
  nbiimpcost NUMBER(9),
  nbirwcost NUMBER(9),
  nbitotcost NUMBER(9),
  nbiyrcost NUMBER(4),
  yearbuilt NUMBER(4),
  yearrecon NUMBER(4),
  histsign CHAR,
  designload CHAR,
  servtypon CHAR,
  servtypund CHAR,
  sumlanes NUMBER(2),
  mainspans NUMBER(3),
  appspans NUMBER(4),
  maxspan FLOAT,
  "LENGTH" FLOAT,
  deck_area FLOAT,
  bridgemed CHAR,
  skew NUMBER(2),
  materialmain CHAR,
  designmain VARCHAR2(2 BYTE),
  materialappr CHAR,
  designappr VARCHAR2(2 BYTE),
  dkstructyp CHAR,
  dkmembtype CHAR,
  dksurftype CHAR,
  dkprotect CHAR,
  deckwidth FLOAT,
  lftcurbsw FLOAT,
  rtcurbsw FLOAT,
  strflared CHAR,
  refvuc CHAR,
  refhuc CHAR,
  hclrurt FLOAT,
  hclrult FLOAT,
  lftbrnavcl FLOAT,
  navcntrol CHAR,
  navhc FLOAT,
  navvc FLOAT,
  paralstruc CHAR,
  tempstruc CHAR,
  nbislen CHAR,
  latitude NUMBER(8,2),
  longitude NUMBER(9,2),
  vclrover FLOAT,
  vclrunder FLOAT,
  placecode VARCHAR2(5 BYTE),
  implen FLOAT,
  fips_state VARCHAR2(2 BYTE),
  tot_length FLOAT,
  nextinspid VARCHAR2(4 BYTE),
  crewhrs NUMBER(8,2),
  flaggerhrs NUMBER(5,2),
  helperhrs NUMBER(5,2),
  snooperhrs NUMBER(5,2),
  spcrewhrs NUMBER(8,2),
  spequiphrs NUMBER(5,2),
  on_off_sys VARCHAR2(1 BYTE),
  ratingdate DATE,
  rater_ini VARCHAR2(3 BYTE),
  orload FLOAT,
  ortype CHAR,
  irload FLOAT,
  irtype CHAR,
  posting CHAR,
  req_op_rat NUMBER(2),
  def_op_rat CHAR,
  fc_detail VARCHAR2(5 BYTE),
  altorload FLOAT,
  altormeth VARCHAR2(4 BYTE),
  altirload FLOAT,
  altirmeth VARCHAR2(4 BYTE),
  otherload FLOAT,
  truck1or FLOAT,
  truck2or FLOAT,
  truck3or FLOAT,
  truck1ir FLOAT,
  truck2ir FLOAT,
  truck3ir FLOAT,
  srstatus CHAR,
  userkey1 VARCHAR2(30 BYTE),
  userkey2 VARCHAR2(30 BYTE),
  userkey3 VARCHAR2(30 BYTE),
  userkey4 VARCHAR2(30 BYTE),
  userkey5 VARCHAR2(30 BYTE),
  userkey6 VARCHAR2(30 BYTE),
  userkey7 VARCHAR2(30 BYTE),
  userkey8 VARCHAR2(30 BYTE),
  userkey9 VARCHAR2(30 BYTE),
  userkey10 VARCHAR2(30 BYTE),
  userkey11 VARCHAR2(30 BYTE),
  userkey12 VARCHAR2(30 BYTE),
  userkey13 VARCHAR2(30 BYTE),
  userkey14 VARCHAR2(30 BYTE),
  userkey15 VARCHAR2(30 BYTE),
  btrigger CHAR,
  traceflag CHAR,
  createdatetime DATE,
  createuserkey VARCHAR2(4 BYTE),
  modtime DATE,
  userkey VARCHAR2(4 BYTE),
  docrefkey VARCHAR2(255 BYTE),
  notes VARCHAR2(2000 BYTE),
  "IMPACT" NUMBER(10,2),
  precise_lat FLOAT,
  precise_lon FLOAT,
  bridge_status VARCHAR2(8 BYTE),
  bridge_lifecycle_phase VARCHAR2(8 BYTE),
  orfactor NUMBER(3,2),
  irfactor NUMBER(3,2)
);