CREATE OR REPLACE PACKAGE pontis.KSBMS_EXC
IS

exc_application_exception EXCEPTION;
en_application_exception CONSTANT PLS_INTEGER := -20000;
PRAGMA EXCEPTION_INIT (exc_application_exception, -20000);
FUNCTION application_exception RETURN PLS_INTEGER;

exc_generic_exception  EXCEPTION;
en_generic_exception CONSTANT PLS_INTEGER := -20300;
PRAGMA EXCEPTION_INIT (exc_generic_exception, -20300);
FUNCTION generic_exception RETURN PLS_INTEGER;

exc_general_cvt_exception EXCEPTION;
en_general_cvt_exception CONSTANT PLS_INTEGER := -20700;
PRAGMA EXCEPTION_INIT (exc_general_cvt_exception, -20700);
FUNCTION general_cvt_exception RETURN PLS_INTEGER;

exc_bad_cvt_factor EXCEPTION;
en_bad_cvt_factor CONSTANT PLS_INTEGER := -20701;
PRAGMA EXCEPTION_INIT (exc_bad_cvt_factor, -20701);
FUNCTION bad_cvt_factor RETURN PLS_INTEGER;

exc_null_cvt_factor EXCEPTION;
en_null_cvt_factor CONSTANT PLS_INTEGER := -20702;
PRAGMA EXCEPTION_INIT (exc_null_cvt_factor, -20702);
FUNCTION null_cvt_factor RETURN PLS_INTEGER;
exc_cvt_factor_missing EXCEPTION;
en_cvt_factor_missing CONSTANT PLS_INTEGER := -20703;
PRAGMA EXCEPTION_INIT (exc_cvt_factor_missing, -20703);
FUNCTION cvt_factor_missing RETURN PLS_INTEGER;
exc_too_many_datadict_rows EXCEPTION;
en_too_many_datadict_rows CONSTANT PLS_INTEGER := -20704;
PRAGMA EXCEPTION_INIT (exc_too_many_datadict_rows, -20704);
FUNCTION too_many_datadict_rows RETURN PLS_INTEGER;
exc_bad_cvt_input_value EXCEPTION;
en_bad_cvt_input_value CONSTANT PLS_INTEGER := -20705;
PRAGMA EXCEPTION_INIT (exc_bad_cvt_input_value, -20705);
FUNCTION bad_cvt_input_value RETURN PLS_INTEGER;
exc_null_cvt_input_value EXCEPTION;
en_null_cvt_input_value CONSTANT PLS_INTEGER := -20706;
PRAGMA EXCEPTION_INIT (exc_null_cvt_input_value, -20706);
FUNCTION null_cvt_input_value RETURN PLS_INTEGER;
exc_fileio_general_exception EXCEPTION;
en_fileio_general_exception CONSTANT PLS_INTEGER := -20100;
PRAGMA EXCEPTION_INIT (exc_fileio_general_exception, -20100);
FUNCTION fileio_general_exception RETURN PLS_INTEGER;
exc_fileio_open_file EXCEPTION;
en_fileio_open_file CONSTANT PLS_INTEGER := -20101;
PRAGMA EXCEPTION_INIT (exc_fileio_open_file, -20101);
FUNCTION fileio_open_file RETURN PLS_INTEGER;
exc_fileio_close_file EXCEPTION;
en_fileio_close_file CONSTANT PLS_INTEGER := -20105;
PRAGMA EXCEPTION_INIT (exc_fileio_close_file, -20105);
FUNCTION fileio_close_file RETURN PLS_INTEGER;
exc_fileio_write_file EXCEPTION;
en_fileio_write_file CONSTANT PLS_INTEGER := -20110;
PRAGMA EXCEPTION_INIT (exc_fileio_write_file, -20110);
FUNCTION fileio_write_file RETURN PLS_INTEGER;
exc_fileio_read_file EXCEPTION;
en_fileio_read_file CONSTANT PLS_INTEGER := -20115;
PRAGMA EXCEPTION_INIT (exc_fileio_read_file, -20115);
FUNCTION fileio_read_file RETURN PLS_INTEGER;
exc_fileio_sysfile_create EXCEPTION;
en_fileio_sysfile_create CONSTANT PLS_INTEGER := -20120;
PRAGMA EXCEPTION_INIT (exc_fileio_sysfile_create, -20120);
FUNCTION fileio_sysfile_create RETURN PLS_INTEGER;
exc_cvt_trigger_upd_failed EXCEPTION;
en_cvt_trigger_upd_failed CONSTANT PLS_INTEGER := -20710;
PRAGMA EXCEPTION_INIT (exc_cvt_trigger_upd_failed, -20710);
FUNCTION cvt_trigger_upd_failed RETURN PLS_INTEGER;
exc_cvt_trigger_insert_failed EXCEPTION;
en_cvt_trigger_insert_failed CONSTANT PLS_INTEGER := -20715;
PRAGMA EXCEPTION_INIT (exc_cvt_trigger_insert_failed, -20715);
FUNCTION cvt_trigger_insert_failed RETURN PLS_INTEGER;
exc_download_script_failed EXCEPTION;
en_download_script_failed CONSTANT PLS_INTEGER := -20210;
PRAGMA EXCEPTION_INIT (exc_download_script_failed, -20210);
FUNCTION download_script_failed RETURN PLS_INTEGER;
exc_msginfo_general EXCEPTION;
en_msginfo_general CONSTANT PLS_INTEGER := -20010;
PRAGMA EXCEPTION_INIT (exc_msginfo_general, -20010);
FUNCTION msginfo_general RETURN PLS_INTEGER;
exc_fw_general EXCEPTION;
en_fw_general CONSTANT PLS_INTEGER := -20030;
PRAGMA EXCEPTION_INIT (exc_fw_general, -20030);
FUNCTION fw_general RETURN PLS_INTEGER;
exc_bms_util_general EXCEPTION;
en_bms_util_general CONSTANT PLS_INTEGER := -20040;
PRAGMA EXCEPTION_INIT (exc_bms_util_general, -20040);
FUNCTION bms_util_general RETURN PLS_INTEGER;
exc_err_general  EXCEPTION;
en_err_general  CONSTANT PLS_INTEGER := -20020;
PRAGMA EXCEPTION_INIT (exc_err_general , -20020);
FUNCTION err_general  RETURN PLS_INTEGER;
exc_bms_exc_general EXCEPTION;
en_bms_exc_general CONSTANT PLS_INTEGER := -20050;
PRAGMA EXCEPTION_INIT (exc_bms_exc_general, -20050);
FUNCTION bms_exc_general RETURN PLS_INTEGER;
exc_fileio_file_not_exist EXCEPTION;
en_fileio_file_not_exist CONSTANT PLS_INTEGER := -20102;
PRAGMA EXCEPTION_INIT (exc_fileio_file_not_exist, -20102);
FUNCTION fileio_file_not_exist RETURN PLS_INTEGER;
exc_bad_nbisync_value EXCEPTION;
en_bad_nbisync_value CONSTANT PLS_INTEGER := -20510;
PRAGMA EXCEPTION_INIT (exc_bad_nbisync_value, -20510);
FUNCTION bad_nbisync_value RETURN PLS_INTEGER;
exc_trg_nbisync_cols_upd EXCEPTION;
en_trg_nbisync_cols_upd CONSTANT PLS_INTEGER := -20500;
PRAGMA EXCEPTION_INIT (exc_trg_nbisync_cols_upd, -20500);
FUNCTION trg_nbisync_cols_upd RETURN PLS_INTEGER;
exc_trg_nbisync_cols_ins EXCEPTION;
en_trg_nbisync_cols_ins CONSTANT PLS_INTEGER := -20501;
PRAGMA EXCEPTION_INIT (exc_trg_nbisync_cols_ins, -20501);
FUNCTION trg_nbisync_cols_ins RETURN PLS_INTEGER;
exc_pontis_version_error EXCEPTION;
en_pontis_version_error CONSTANT PLS_INTEGER := -20001;
PRAGMA EXCEPTION_INIT (exc_pontis_version_error, -20001);
FUNCTION pontis_version_error RETURN PLS_INTEGER;
exc_null_cvt_result EXCEPTION;
en_null_cvt_result CONSTANT PLS_INTEGER := -20707;
PRAGMA EXCEPTION_INIT (exc_null_cvt_result, -20707);
FUNCTION null_cvt_result RETURN PLS_INTEGER;
exc_zero_cvt_result EXCEPTION;
en_zero_cvt_result CONSTANT PLS_INTEGER := -20708;
PRAGMA EXCEPTION_INIT (exc_zero_cvt_result, -20708);
FUNCTION zero_cvt_result RETURN PLS_INTEGER;
exc_bad_cvt_dec_plcs EXCEPTION;
en_bad_cvt_dec_plcs CONSTANT PLS_INTEGER := -20709;
PRAGMA EXCEPTION_INIT (exc_bad_cvt_dec_plcs, -20709);
FUNCTION bad_cvt_dec_plcs RETURN PLS_INTEGER;
END KSBMS_EXC;

 
/