CREATE OR REPLACE TRIGGER pontis.TAUR_USERRWAY_NBI_47_UNDR
	AFTER UPDATE OF HCLR_E, HCLR_W, HCLR_N, HCLR_S ON pontis.USERRWAY
	FOR EACH ROW
	

  WHEN (new.on_under <>'1') DECLARE V_HCLRINV_NBI ROADWAY.HCLRINV%TYPE;
		TEMPHCLR_N ROADWAY.HCLRINV%TYPE;
		TEMPHCLR_E ROADWAY.HCLRINV%TYPE;
		TEMPHCLR_S ROADWAY.HCLRINV%TYPE;
		TEMPHCLR_W ROADWAY.HCLRINV%TYPE;
BEGIN

IF  (:NEW.HCLR_N IS NULL OR :NEW.HCLR_N <= 0 )then
	TEMPHCLR_N := 99999;
  else
    	TEMPHCLR_N := :NEW.HCLR_N;
  end if;

  IF (:NEW.HCLR_E IS NULL OR :NEW.HCLR_E <= 0 ) then
  	TEMPHCLR_E := 99999;
  else
      	TEMPHCLR_E := :NEW.HCLR_E;
  end if;
 IF  (:NEW.HCLR_S IS NULL OR :NEW.HCLR_S <= 0 ) then
  	TEMPHCLR_S := 99999;
  else
      	TEMPHCLR_S := :NEW.HCLR_S;
  end if;
IF   (:NEW.HCLR_W IS NULL OR :NEW.HCLR_W <= 0 ) then
 	TEMPHCLR_W := 99999;
  else
    	TEMPHCLR_W := :NEW.HCLR_W;
  end if;

  V_HCLRINV_NBI := round(least( TEMPHCLR_N, TEMPHCLR_E, TEMPHCLR_S, TEMPHCLR_W),4);

  If V_HCLRINV_NBI = 99999 then
     V_HCLRINV_NBI := 0;



end if;
-- Now, Put This Horizontal Clearance into the Pontis ROADWAY Table;
UPDATE ROADWAY
	SET HCLRINV = V_HCLRINV_NBI
	WHERE
	ROADWAY.BRKEY = :OLD.BRKEY
      AND ROADWAY.ON_UNDER = :OLD.ON_UNDER;

END TAUR_USERRWAY_NBI_47_UNDR;
/