CREATE OR REPLACE TRIGGER pontis.TAUR_USERBRDG_NBI_63
	AFTER UPDATE OF ORLOAD_HL93,ORLOAD_ADJ_HS,ORLOAD_LFD_HS,ORLOAD_WSD_HS ON pontis.USERBRDG

  FOR EACH ROW


  




DECLARE V_BRIDGE_NBI_63 BRIDGE.ORTYPE%TYPE;
   
BEGIN

IF (NVL(:NEW.ORLOAD_HL93,0) > 0) THEN
  V_BRIDGE_NBI_63:='8';
END IF;

IF (NVL(:NEW.ORLOAD_HL93,0) <= 0)  THEN
 IF ( NVL(:NEW.ORLOAD_LFD_HS,0) > 0 ) THEN
    V_BRIDGE_NBI_63:='1';
ELSIF
  (NVL(:NEW.ORLOAD_LFD_HS,0) = 0) and (:NEW.ORLOAD_WSD_HS > 0) THEN
  V_BRIDGE_NBI_63:='2';
  ELSE
    V_BRIDGE_NBI_63:='5';
    END IF;
 END if;


-- Now, put this value into the bridge nbi 63 field
UPDATE BRIDGE
  SET ORTYPE = V_BRIDGE_NBI_63
  WHERE
  BRIDGE.BRKEY = :OLD.BRKEY;

END TAUR_USERBRDG_NBI_63;
/