CREATE OR REPLACE TRIGGER pontis.TAUR_USERRWAY_TOLLFAC_NBI20
	AFTER UPDATE OF TOLL_KDOT ON pontis.USERRWAY
	FOR EACH ROW
	

  WHEN (NEW.ON_UNDER = '1') DECLARE  v_nbi_result_code ROADWAY.TOLLFAC%TYPE;
BEGIN

-- Look up the NBI code for the KDOT field 
v_nbi_result_code := get_nbicode_from_NBILookup( 'USERRWAY', 'TOLL_KDOT', :new.TOLL_KDOT );

UPDATE ROADWAY
  SET TOLLFAC = V_NBI_RESULT_CODE
  WHERE
  ROADWAY.BRKEY = :OLD.BRKEY AND
  ROADWAY.ON_UNDER in ('1','2','A','B','C');

END TAUR_USERRWAY_TOLLFAC_NBI20;
/