CREATE OR REPLACE TRIGGER pontis.TAUR_USERBRDG_NBI_65
  AFTER UPDATE OF IRLOAD_HL93,IRLOAD_ADJ_HS,IRLOAD_LFD_HS,IRLOAD_WSD_HS ON pontis.USERBRDG

  FOR EACH ROW


  




DECLARE V_BRIDGE_NBI_65 BRIDGE.IRTYPE%TYPE;
   
BEGIN

IF (NVL(:NEW.IRLOAD_HL93,0) > 0) THEN
  V_BRIDGE_NBI_65:='8';
END IF;

IF (NVL(:NEW.IRLOAD_HL93,0) <= 0)  THEN
 IF ( NVL(:NEW.IRLOAD_LFD_HS,0) > 0 ) THEN
    V_BRIDGE_NBI_65:='1';
ELSIF
  (NVL(:NEW.IRLOAD_LFD_HS,0) = 0) and (:NEW.IRLOAD_WSD_HS > 0) THEN
  V_BRIDGE_NBI_65:='2';
  ELSE
    V_BRIDGE_NBI_65:='5';
    END IF;
 END if;


-- Now, put this value into the bridge nbi 63 field
UPDATE BRIDGE
  SET IRTYPE = V_BRIDGE_NBI_65
  WHERE
  BRIDGE.BRKEY = :OLD.BRKEY;

END TAUR_USERBRDG_NBI_65;
/