CREATE MATERIALIZED VIEW pontis.mv_deck_study_mostrecent (brkey,elemkey,inspdate,dkrating,strunitkey,envkey,strtype,qty,units,qtystate1,qtystate2,qtystate3,qtystate4,qtystate5,wearing_surface,deck_material,rail,dk_deter_top,dk_deter_btm,ws_thickness,deck_thickness,crit_note_1,crit_note_2,sealer,"PROTECTION",membrane,drainage,yearbuilt,newsuper,newdeck,widening,inspkey)
REFRESH START WITH TO_DATE('2016-5-22 3:0:0', 'yyyy-mm-dd hh24:mi:ss') NEXT NEXT_DAY(TRUNC(SYSDATE),'SUNDAY') + 3/24 
AS SELECT B.BRKEY,
       E.ELEMKEY,
       I.INSPDATE,
       i.DKRATING,
         E.STRUNITKEY,
         E.ENVKEY,
         f_structuretype(us.brkey,us.strunitkey) AS STRTYPE,
         ROUND(E.QUANTITY / P.FACTOR) AS QTY,
         P.ENGLISHUNIT AS UNITS,
         ROUND(E.QTYSTATE1 / P.FACTOR) AS QTYSTATE1,
         ROUND(E.QTYSTATE2 / P.FACTOR) AS QTYSTATE2,
         ROUND(E.QTYSTATE3 / P.FACTOR) AS QTYSTATE3,
         ROUND(E.QTYSTATE4 / P.FACTOR) AS QTYSTATE4,
         ROUND(E.QTYSTATE5 / P.FACTOR) AS QTYSTATE5,
           F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DKSURFTYPE',US.DKSURFTYPE) AS WEARING_SURFACE,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DECK_MATRL',US.DECK_MATRL) AS DECK_MATERIAL,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','RAIL_TYPE',US.RAIL_TYPE) AS RAIL,
         US.DK_TOP_DELAMS AS DK_DETER_TOP,
         US.DK_DETER_BTM,
         ROUND(US.WEAR_THICK/25.4,1) AS WS_THICKNESS,
         ROUND(US.DECK_THICK/25.4,1) AS DECK_THICKNESS,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','CRIT_NOTE_DK',US.CRIT_NOTE_DK_1) AS CRIT_NOTE_1,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','CRIT_NOTE_DK',US.CRIT_NOTE_DK_2) AS CRIT_NOTE_2,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DECKSEAL',US.DECKSEAL) AS SEALER,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DKPROTECT',US.DKPROTECT) AS PROTECTION,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DKMEMBTYPE',US.DKMEMBTYPE) AS MEMBRANE,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DK_DRAIN_SYS',US.DK_DRAIN_SYS) AS DRAINAGE,
         B.YEARBUILT,
         V.NEWSUPER,
         V.NEWDECK,
         V.WIDENING,
         E.INSPKEY

FROM pontis.ELEMINSP E,
         pontis.ELEMDEFS,
         pontis.INSPEVNT I,
         pontis.USERSTRUNIT US,
         pontis.METRIC_ENGLISH P ,
         pontis.MV_LATEST_INSPECTION MV,
         pontis.BRIDGE B,
         V_DECK_STUDY V
   WHERE P.PAIRCODE = pontis.ELEMDEFS.PAIRCODE and
         pontis.ELEMDEFS.ELEMKEY = E.ELEMKEY and
         V.BRKEY = B.BRKEY AND
         E.BRKEY = B.BRKEY AND
         I.BRKEY = B.BRKEY AND
         MV.BRKEY = B.BRKEY AND
         E.INSPKEY = MV.INSPKEY AND
         I.INSPKEY = MV.INSPKEY AND
         US.BRKEY = B.BRKEY AND
         US.STRUNITKEY = E.STRUNITKEY AND
         ELEMDEFS.ELEMNUM IN (12, 13, 14, 18, 22, 26, 27, 28, 29, 30, 31, 32, 38, 39, 40, 44, 48, 52, 53, 54, 55,
           358, 359) AND
          B.DISTRICT <> '9' AND
          SUBSTR(B.BRKEY,4,1) <> '5'
      --  and  B.YEARBUILT <> '1000'
 UNION ALL
  SELECT B.BRKEY,
       E.ELEMKEY,
       I.INSPDATE,
       i.DKRATING,
         E.STRUNITKEY,
         E.ENVKEY,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','UNIT_MATERIAL',US.UNIT_MATERIAL)||
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','UNIT_TYPE',US.UNIT_TYPE)||
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','SUPER_DESIGN_TY',US.SUPER_DESIGN_TY) AS STRTYPE,
         ROUND(E.QUANTITY / P.FACTOR) AS QTY,
         P.ENGLISHUNIT AS UNITS,
         ROUND(E.QTYSTATE1 / P.FACTOR) AS QTYSTATE1,
         ROUND(E.QTYSTATE2 / P.FACTOR) AS QTYSTATE2,
         ROUND(E.QTYSTATE3 / P.FACTOR) AS QTYSTATE3,
         ROUND(E.QTYSTATE4 / P.FACTOR) AS QTYSTATE4,
         ROUND(E.QTYSTATE5 / P.FACTOR) AS QTYSTATE5,
           F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DKSURFTYPE',US.DKSURFTYPE) AS WEARING_SURFACE,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DECK_MATRL',US.DECK_MATRL) AS DECK_MATERIAL,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','RAIL_TYPE',US.RAIL_TYPE) AS RAIL,
         US.DK_TOP_DELAMS AS DK_DETER_TOP,
         US.DK_DETER_BTM,
         ROUND(US.WEAR_THICK/25.4,1) AS WS_THICKNESS,
         ROUND(US.DECK_THICK/25.4,1) AS DECK_THICKNESS,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','CRIT_NOTE_DK',US.CRIT_NOTE_DK_1) AS CRIT_NOTE_1,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','CRIT_NOTE_DK',US.CRIT_NOTE_DK_2) AS CRIT_NOTE_2,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DECKSEAL',US.DECKSEAL) AS SEALER,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DKPROTECT',US.DKPROTECT) AS PROTECTION,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DKMEMBTYPE',US.DKMEMBTYPE) AS MEMBRANE,
         F_GET_PARAMTRS_EQUIV_LONG('USERSTRUNIT','DK_DRAIN_SYS',US.DK_DRAIN_SYS) AS DRAINAGE,
         B.YEARBUILT,
         V.NEWSUPER,
         V.NEWDECK,
         V.WIDENING,
         E.INSPKEY

FROM pontis.ELEMINSP E,
         pontis.ELEMDEFS,
         pontis.INSPEVNT I,
         pontis.USERSTRUNIT US,
         pontis.METRIC_ENGLISH P ,
         pontis.MV_LATEST_INSPECTION MV,
         pontis.BRIDGE B,
         V_DECK_STUDY V
   WHERE P.PAIRCODE = pontis.ELEMDEFS.PAIRCODE and
         pontis.ELEMDEFS.ELEMKEY = E.ELEMKEY and
         V.BRKEY = B.BRKEY AND
         E.BRKEY = B.BRKEY AND
         I.BRKEY = B.BRKEY AND
         MV.BRKEY = B.BRKEY AND
         E.INSPKEY = MV.INSPKEY AND
         I.INSPKEY = MV.INSPKEY AND
         US.BRKEY = B.BRKEY AND
         US.STRUNITKEY = E.STRUNITKEY AND
         ELEMDEFS.ELEMNUM IN (12, 13, 14, 18, 22, 26, 27, 28, 29, 30, 31, 32, 38, 39, 40, 44, 48, 52, 53, 54, 55,
           358, 359) AND
          B.DISTRICT <> '9' AND
          SUBSTR(B.BRKEY,4,1) = '5' AND
          length(f_structuretype(us.brkey,us.strunitkey)) <> 3
     --   and  B.YEARBUILT <> '1000'
;