CREATE TABLE ksbms_robot.plan_table (
  "STATEMENT_ID" VARCHAR2(30 BYTE),
  "TIMESTAMP" DATE,
  remarks VARCHAR2(80 BYTE),
  operation VARCHAR2(30 BYTE),
  options VARCHAR2(30 BYTE),
  object_node VARCHAR2(128 BYTE),
  object_owner VARCHAR2(30 BYTE),
  object_name VARCHAR2(30 BYTE),
  object_instance NUMBER,
  object_type VARCHAR2(30 BYTE),
  optimizer VARCHAR2(255 BYTE),
  search_columns NUMBER,
  "ID" NUMBER,
  parent_id NUMBER,
  position NUMBER,
  "COST" NUMBER,
  "CARDINALITY" NUMBER,
  bytes NUMBER,
  other_tag VARCHAR2(255 BYTE),
  partition_start VARCHAR2(255 BYTE),
  partition_stop VARCHAR2(255 BYTE),
  partition_id NUMBER,
  "OTHER" LONG,
  distribution VARCHAR2(30 BYTE)
);