CREATE OR REPLACE FORCE VIEW pontis.v_compliance_mar6 (brkey,bridge_id,culvert_flag,district,yearbuilt,servtypon,function_type,latest_inspkey,oppostcl,inspdate,nextdate,months_overdue,inspfreq_years,inspfreq_months) AS
SELECT (B.BRKEY),
       B.BRIDGE_ID "BRIDGE_ID",
       CASE WHEN  INSTR(BRIDGE_ID, 'C') > 0 THEN 'C' ELSE NULL END  "CULVERT_FLAG",
       F_GET_PARAMTRS_EQUIV('BRIDGE','DISTRICT',B.DISTRICT)  "DISTRICT",
       B.YEARBUILT "YEARBUILT",
       F_GET_PARAMTRS_EQUIV('BRIDGE','SERVTYPON',B.SERVTYPON) "SERVTYPON",
       F_GET_PARAMTRS_EQUIV('USERBRDG','FUNCTION_TYPE',UB.FUNCTION_TYPE) "FUNCTION_TYPE",
       MV.INSPKEY "LATEST_INSPKEY",
       I.OPPOSTCL "OPPOSTCL",
       I.INSPDATE "INSPDATE",
       MV.NEXTRINSP_CALC "NEXTDATE",
       NVL( F_COMPLIANCE_MAR6(B.BRKEY), 0) "MONTHS_OVERDUE",
       UI.BRINSPFREQ_KDOT "INSPFREQ_YEARS",
       TRUNC(UI.BRINSPFREQ_KDOT * 12) AS "INSPFREQ_MONTHS"
  FROM BRIDGE B
 INNER JOIN USERBRDG UB
    ON B.BRKEY = UB.BRKEY
 INNER JOIN MV_LATEST_INSPECTION MV
    ON B.BRKEY = MV.BRKEY
 INNER JOIN INSPEVNT I
    ON B.BRKEY = I.BRKEY
   AND I.INSPKEY = MV.INSPKEY
 INNER JOIN USERINSP UI
    ON UI.BRKEY = B.BRKEY
   AND UI.INSPKEY = MV.INSPKEY
 WHERE B.DISTRICT NOT IN ('9', '09')
   AND I.OPPOSTCL <> '5'
   AND UB.FUNCTION_TYPE IN ('10', '30', '50', '51', '70')
   AND B.YEARBUILT <> '1000' AND UI.BRINSPFREQ_KDOT <>0.0
;