CREATE OR REPLACE FORCE VIEW pontis.v_fc_structures (brkey,bridge_id) AS
(SELECT BRIDGE.BRKEY,
       BRIDGE.BRIDGE_ID
FROM   pontis.BRIDGE
WHERE BRKEY IN (SELECT DISTINCT BRKEY FROM
pontis.USERSTRUNIT U
WHERE U.BRKEY = BRIDGE.BRKEY AND
      (U.CRIT_NOTE_SUP_1 = '1' OR
       U.CRIT_NOTE_SUP_2 = '1' OR
       U.CRIT_NOTE_SUP_3 = '1' OR
       U.CRIT_NOTE_SUP_4 = '1' OR
       U.CRIT_NOTE_SUP_5 = '1' ) AND
       SUBSTR(BRIDGE.BRKEY,4,1) <> '5'))

 ;