CREATE OR REPLACE FORCE VIEW pontis.v_kaws_structures_eng (serialnumber,co_ser,structure_id,district,area,subarea,route_prefix,route,ref_point,loc_desc,orientation,latitude,longitude,marked_text,marked_no,strtype,"OWNER",pole_height,arm_truss_span,county_fipps,attached,vertclr,signrtfttype,signltfttype,anchorboltno,anchorboltspacing,anchorboltdiam,anchorboltlength_design,baseplateshape,baseplatewidth,baseplatethick,attach_catwalk,attach_electric,attach_lighting,attach_downarrows,attach_other_desc,attach_other,geogloc,standoffdist,notes) AS
select serialnumber            ,
  co_ser                  ,
  structure_id            ,
  district                ,
  area                    ,
  subarea                 ,
  route_prefix            ,
  route                   ,
  ref_point               ,
  loc_desc                ,
  orientation             ,
  latitude                ,
  longitude               ,
  marked_text             ,
  marked_no               ,
 f_get_kaws_prmtrs_equiv_l('KAWS_STRUCTURES','MATRL_TYPE',MATRL_TYPE)||f_get_kaws_prmtrs_equiv_l('KAWS_STRUCTURES','SUPR_TYPE',SUPR_TYPE)||'-'||
 f_get_kaws_prmtrs_equiv_s('KAWS_STRUCTURES','SUPR_TYPE',SUPR_TYPE) AS STRTYPE,
  owner                   ,
  pole_height / .3048 pole_height            ,
  arm_truss_span          ,
  county_fipps            ,
  attached                ,
  vertclr /.3048 vertclr                ,
  signrtfttype            ,
  signltfttype            ,
  anchorboltno            ,
  anchorboltspacing /25.4  anchorboltspacing    ,
  anchorboltdiam / 25.4 anchorboltdiam         ,
  anchorboltlength_design / 25.4 anchorboltlength_design,
  baseplateshape          ,
  baseplatewidth  / 25.4 baseplatewidth       ,
  baseplatethick   / 25.4 baseplatethick       ,
  attach_catwalk          ,
  attach_electric         ,
  attach_lighting         ,
  attach_downarrows       ,
  attach_other_desc       ,
  attach_other            ,
  geogloc                 ,
  standoffdist / 25.4 standoffdist          ,
  notes
from kaws_structures
;