CREATE OR REPLACE FORCE VIEW pontis.v_bridge_proj_witems (bridge_id,brkey,project_id,projname,progyear,proj_status,reviewed_by,review_status,prog_id,progname,work_items_count) AS
SELECT BRIDGE.BRIDGE_ID BRIDGE_ID, BRIDGE.BRKEY BRKEY, PROJECTS.PROJECT_ID PROJECT_ID, PROJECTS.PROJNAME PROJNAME, PROJECTS.PROGYEAR PROGYEAR, PROJECTS.PROJ_STATUS PROJ_STATUS, PROJECTS.PROJ_REVIEWED_BY REVIEWED_BY, PROJECTS.PROJ_REVIEW_STATUS REVIEW_STATUS, PRJ_PROGRAMS.PROG_ID PROG_ID, PRJ_PROGRAMS.PROGNAME PROGNAME, COUNT( PRJ_WITEMS.WITEMKEY ) WORK_ITEMS_COUNT
            FROM BRIDGE,
                    PRJ_WITEMS,
                    PROJECTS,
                    PRJ_PROGRAMS
            WHERE BRIDGE.BRKEY = PRJ_WITEMS.BRKEY AND
                      PROJECTS.PROJKEY = PRJ_WITEMS.PROJKEY AND
                      PRJ_PROGRAMS.PROGKEY = PROJECTS.PROGKEY
            GROUP BY BRIDGE.BRIDGE_ID,
                    BRIDGE.BRKEY,
                    PROJECTS.PROJECT_ID,
                    PROJECTS.PROJNAME,
                    PROJECTS.PROGYEAR,
                    PROJECTS.PROJ_STATUS,
                    PROJECTS.PROJ_REVIEWED_BY,
                    PROJECTS.PROJ_REVIEW_STATUS,
                    PRJ_PROGRAMS.PROG_ID,
                    PRJ_PROGRAMS.PROGNAME;