CREATE OR REPLACE FORCE VIEW pontis.v_kdot_hi (brkey,yearbuilt,length_eng,avg_hi) AS
(SELECT BRIDGE.BRKEY,
        BRIDGE.YEARBUILT,
        BRIDGE.LENGTH / .3048 AS LENGTH_ENG,
        USERBRDG.AVG_HI
    FROM pontis.BRIDGE, pontis.USERBRDG
   WHERE BRIDGE.BRKEY = USERBRDG.BRKEY AND
         USERBRDG.AVG_HI IS NOT NULL and
         SUBSTR(BRIDGE.BRKEY,4,1) <> '5' AND
         BRIDGE.YEARBUILT <> '1000' AND
         BRIDGE.BRKEY NOT IN ('022028','022029','046314','105067','105151','105166'))

 ;