CREATE OR REPLACE FORCE VIEW pontis.v_kta_structures (brkey,oppostcl_kdot,userkey15,owner_kdot,custodian_kdot) AS
SELECT  B.BRKEY, OPPOSTCL_KDOT, USERKEY15, UB.OWNER_KDOT, UB.CUSTODIAN_KDOT
FROM pontis.BRIDGE B, pontis.USERINSP US, pontis.MV_LATEST_INSPECTION MV, USERBRDG UB
WHERE US.BRKEY = B.BRKEY AND
      UB.BRKEY = B.BRKEY AND
      MV.BRKEY = B.BRKEY AND
      US.INSPKEY = MV.INSPKEY AND
      US.BRINSPFREQ_KDOT = 99

 ;