CREATE OR REPLACE FORCE VIEW pontis.v_multi_unit_structures (brkey,avg_hi) AS
SELECT BRKEY, AVG_HI FROM pontis.USERBRDG WHERE  AVG_HI IS NOT NULL AND BRKEY IN (SELECT DISTINCT BRKEY FROM pontis.STRUCTURE_UNIT S  WHERE S.BRKEY = USERBRDG.BRKEY AND  STRUNITKEY > '1')  ORDER BY BRKEY

 ;