CREATE OR REPLACE FORCE VIEW pontis.v_sd_structures (brkey,inspdate,inspkey,nbi_rating) AS
SELECT DISTINCT INSPEVNT.BRKEY,
       INSPEVNT.INSPDATE,
       INSPEVNT.INSPKEY,
       INSPEVNT.NBI_RATING
FROM   pontis.INSPEVNT
WHERE NBI_RATING = '1'
ORDER BY INSPDATE DESC

 ;