CREATE TABLE pontis.pon_nav_task (
  tab_id NUMBER(38) NOT NULL,
  task_id NUMBER(38) NOT NULL,
  "NAME" VARCHAR2(32 BYTE),
  parent_task_id NUMBER(38),
  label_caption_id NUMBER(38) NOT NULL,
  order_num NUMBER(38) NOT NULL,
  visible_ind CHAR NOT NULL,
  read_only_ind CHAR NOT NULL,
  navigate_url VARCHAR2(256 BYTE),
  image_url VARCHAR2(256 BYTE),
  skin_id VARCHAR2(64 BYTE),
  css_class VARCHAR2(64 BYTE),
  tooltip_caption_id NUMBER(38),
  popup_task_ind CHAR,
  navigate_target_type VARCHAR2(32 BYTE),
  task_gui_resource_id VARCHAR2(256 BYTE),
  width VARCHAR2(16 BYTE),
  height VARCHAR2(16 BYTE),
  resizable_ind CHAR,
  status_bar_ind CHAR,
  scroll_bars_ind CHAR,
  help_url VARCHAR2(256 BYTE),
  pontis_standard_ind CHAR,
  CONSTRAINT pon_nav_task_pk PRIMARY KEY (tab_id,task_id) DISABLE NOVALIDATE,
  CONSTRAINT fk_nav_task_recursive FOREIGN KEY (tab_id,parent_task_id) REFERENCES pontis.pon_nav_task (tab_id,task_id) DISABLE NOVALIDATE,
  CONSTRAINT fk_nav_task_to_caption FOREIGN KEY (label_caption_id) REFERENCES pontis.pon_app_caption (caption_id) DISABLE NOVALIDATE,
  CONSTRAINT fk_nav_task_to_caption_two FOREIGN KEY (tooltip_caption_id) REFERENCES pontis.pon_app_caption (caption_id) DISABLE NOVALIDATE,
  CONSTRAINT fk_nav_task_to_tab FOREIGN KEY (tab_id) REFERENCES pontis.pon_nav_tab (tab_id) DISABLE NOVALIDATE
);