CREATE TABLE pontis.pon_layouts (
  layoutkey NUMBER(38) NOT NULL,
  userkey NUMBER(38) NOT NULL,
  "NAME" VARCHAR2(100 BYTE) NOT NULL,
  "SHARED" NUMBER(38) DEFAULT 0 NOT NULL,
  "CONTEXT" VARCHAR2(32 BYTE) DEFAULT 'BRIDGES' NOT NULL,
  sql_query VARCHAR2(2000 BYTE) NOT NULL,
  notes VARCHAR2(2000 BYTE),
  pontis_standard_ind CHAR DEFAULT 'F' NOT NULL,
  layout_type NUMBER(38) DEFAULT 0 NOT NULL,
  CONSTRAINT pon_layouts_pk PRIMARY KEY (layoutkey) DISABLE NOVALIDATE,
  CONSTRAINT fk_pon_layouts_516_users FOREIGN KEY (userkey) REFERENCES pontis.pon_app_users (userkey) ON DELETE CASCADE DISABLE NOVALIDATE
);