CREATE TABLE pontis.pon_elem_insp (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  inspkey VARCHAR2(4 BYTE) NOT NULL,
  elem_key NUMBER(4) NOT NULL,
  elem_parent_key NUMBER(4) NOT NULL,
  envkey NUMBER(1) NOT NULL,
  strunitkey NUMBER(4) NOT NULL,
  elem_quantity FLOAT NOT NULL,
  elem_scale_factor FLOAT DEFAULT 1,
  elem_pctstate1 FLOAT NOT NULL,
  elem_pctstate2 FLOAT NOT NULL,
  elem_pctstate3 FLOAT NOT NULL,
  elem_pctstate4 FLOAT NOT NULL,
  elem_qtystate1 FLOAT NOT NULL,
  elem_qtystate2 FLOAT NOT NULL,
  elem_qtystate3 FLOAT NOT NULL,
  elem_qtystate4 FLOAT NOT NULL,
  elem_desc VARCHAR2(255 BYTE),
  elem_createdatetime DATE DEFAULT SYSDATE,
  elem_createuserkey VARCHAR2(4 BYTE),
  elem_modtime DATE DEFAULT SYSDATE,
  elem_moduserkey VARCHAR2(4 BYTE),
  elem_docrefkey VARCHAR2(255 BYTE),
  elem_notes VARCHAR2(2000 BYTE),
  elem_grandparent_key NUMBER(4) DEFAULT 0 NOT NULL,
  CONSTRAINT pon_elem_insp_pk PRIMARY KEY (brkey,inspkey,elem_key,elem_parent_key,envkey,strunitkey,elem_grandparent_key),
  CONSTRAINT fk_pon_elem_insp_elemdefs FOREIGN KEY (elem_key) REFERENCES pontis.pon_elem_defs (elem_key),
  CONSTRAINT fk_pon_elem_insp_envtdefs FOREIGN KEY (envkey) REFERENCES pontis.envtdefs (envkey),
  CONSTRAINT fk_pon_elem_insp_inspevnt FOREIGN KEY (brkey,inspkey) REFERENCES pontis.inspevnt (brkey,inspkey) ON DELETE CASCADE
);