CREATE TABLE pontis.randr (
  state_name VARCHAR2(6 BYTE),
  fed_agency CHAR,
  strnum VARCHAR2(15 BYTE) NOT NULL,
  invenroute VARCHAR2(15 BYTE),
  featint VARCHAR2(24 BYTE),
  "FACILITY" VARCHAR2(18 BYTE),
  "LOCATION" VARCHAR2(25 BYTE),
  county_code VARCHAR2(3 BYTE),
  county_name VARCHAR2(15 BYTE),
  hgwy_dist VARCHAR2(2 BYTE),
  "OWNER" VARCHAR2(2 BYTE),
  func_class VARCHAR2(2 BYTE),
  yearbuilt VARCHAR2(4 BYTE),
  adt VARCHAR2(6 BYTE),
  posted VARCHAR2(2 BYTE),
  str_length FLOAT,
  deck_width FLOAT,
  area_of_str FLOAT,
  operrating FLOAT,
  invrating FLOAT,
  postingeval CHAR,
  strahnet_hwy CHAR,
  highway_sys CHAR,
  sdfo VARCHAR2(2 BYTE),
  suff_astrsk CHAR,
  suffrate FLOAT,
  brkey VARCHAR2(15 BYTE)
);