CREATE TABLE pontis.tblnewcansys (
  county FLOAT,
  "SERIAL" FLOAT,
  prefix VARCHAR2(255 BYTE),
  route FLOAT,
  suffix VARCHAR2(255 BYTE),
  routeunique_id FLOAT,
  route_id FLOAT,
  ref_pt FLOAT,
  fctyp FLOAT,
  sftyp FLOAT,
  brorient FLOAT,
  direct FLOAT,
  directionid FLOAT,
  deck VARCHAR2(255 BYTE),
  super VARCHAR2(255 BYTE),
  sub VARCHAR2(255 BYTE),
  culv VARCHAR2(255 BYTE),
  bci FLOAT,
  destrk FLOAT,
  deswt FLOAT,
  vclt FLOAT,
  vcrt FLOAT,
  uclt FLOAT,
  ucrt FLOAT,
  yrbuilt FLOAT,
  yrrpr FLOAT,
  supermat FLOAT,
  supertyp FLOAT,
  superdes FLOAT,
  ng FLOAT,
  fill FLOAT,
  "SIGN" FLOAT,
  dist FLOAT,
  area FLOAT,
  aadt FLOAT,
  spc1 FLOAT,
  spc2 FLOAT,
  "OWNER" FLOAT,
  roadway FLOAT,
  "FUNCTION" VARCHAR2(255 BYTE),
  feature VARCHAR2(255 BYTE),
  locdesc VARCHAR2(255 BYTE),
  suffrate FLOAT,
  inspint FLOAT,
  projnum VARCHAR2(255 BYTE),
  projwork VARCHAR2(255 BYTE),
  letdate VARCHAR2(255 BYTE),
  painttons FLOAT,
  painttype FLOAT,
  paintyear FLOAT,
  paintcond FLOAT,
  lastinsp DATE,
  ponum FLOAT,
  brkey VARCHAR2(255 BYTE)
);