CREATE TABLE pontis.userinsp (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  inspkey VARCHAR2(4 BYTE) NOT NULL,
  cond_index NUMBER(*,0),
  brinspfreq_kdot NUMBER(3,1),
  accept_date DATE,
  deduct_code CHAR,
  fhwa_status CHAR,
  fcinspfreq_kdot NUMBER(3,1),
  r_inspname_1 VARCHAR2(4 BYTE),
  r_inspname_2 VARCHAR2(4 BYTE),
  r_inspname_3 VARCHAR2(4 BYTE),
  r_inspname_4 VARCHAR2(4 BYTE),
  f_inspname_1 VARCHAR2(4 BYTE),
  f_inspname_2 VARCHAR2(4 BYTE),
  f_inspname_3 VARCHAR2(4 BYTE),
  f_inspname_4 VARCHAR2(4 BYTE),
  rs_inspname_1 VARCHAR2(4 BYTE),
  rs_inspname_2 VARCHAR2(4 BYTE),
  rs_inspname_3 VARCHAR2(4 BYTE),
  rs_inspname_4 VARCHAR2(4 BYTE),
  uw_inspname_1 VARCHAR2(4 BYTE),
  uw_inspname_2 VARCHAR2(4 BYTE),
  uw_inspname_3 VARCHAR2(4 BYTE),
  uw_inspname_4 VARCHAR2(4 BYTE),
  ph_inspname_1 VARCHAR2(4 BYTE),
  ph_inspname_2 VARCHAR2(4 BYTE),
  ph_inspname_3 VARCHAR2(4 BYTE),
  ph_inspname_4 VARCHAR2(4 BYTE),
  osinspfreq_kdot NUMBER(3,1),
  paint_cond VARCHAR2(2 BYTE),
  snoop_insp_freq NUMBER(3,1),
  snoop_last_insp DATE,
  snoop_insp_done CHAR,
  snoop_insp_req CHAR,
  rep_review_by VARCHAR2(25 BYTE),
  rep_revby_date DATE,
  uwinspfreq_kdot NUMBER(3,1),
  uwater_insp_typ CHAR,
  oppostcl_kdot VARCHAR2(4 BYTE),
  fcinspreq_kdot CHAR,
  deck_comp_hi NUMBER(5,1),
  super_comp_hi NUMBER(5,1),
  sub_comp_hi NUMBER(5,1),
  culv_comp_hi NUMBER(5,1),
  deck_hi NUMBER(5,1),
  structure_hi NUMBER(5,1),
  priority_opt NUMBER(6,4),
  snoop_next_insp DATE,
  spcl_last_insp DATE,
  spcl_next_insp DATE,
  spcl_insp_type VARCHAR2(2 BYTE),
  spcl_insp_freq NUMBER(3,1),
  crtcl_find_date DATE,
  crtcl_find_comp DATE,
  crtcl_comments VARCHAR2(2000 BYTE),
  scour_find_date DATE,
  scour_find_comp DATE,
  scour_comments VARCHAR2(2000 BYTE),
  createdatetime DATE,
  createuserkey VARCHAR2(4 BYTE),
  modtime DATE,
  userkey VARCHAR2(4 BYTE),
  notes VARCHAR2(2000 BYTE),
  CONSTRAINT userinsp_pk PRIMARY KEY (brkey,inspkey),
  CONSTRAINT fk_userinsp_46_inspevnt FOREIGN KEY (brkey,inspkey) REFERENCES pontis.inspevnt (brkey,inspkey) ON DELETE CASCADE
);
COMMENT ON COLUMN pontis.userinsp.fhwa_status IS 'Field to house eligibility status of a structure as mandated by the FHWA (Y or N)';