CREATE TABLE pontis.vc_inspevnt (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  inspkey VARCHAR2(4 BYTE),
  inspdate DATE NOT NULL,
  inspname VARCHAR2(24 BYTE) NOT NULL,
  inspusrkey VARCHAR2(4 BYTE) NOT NULL,
  rev_req CHAR,
  det_upd CHAR,
  inspectcontrolid VARCHAR2(20 BYTE),
  nbinspdone CHAR,
  brinspfreq NUMBER(2),
  lastinsp DATE,
  nextinsp DATE,
  elinspdone CHAR,
  elinspfreq NUMBER(2),
  elinspdate DATE,
  elnextdate DATE,
  uwinspreq CHAR,
  uwinspdone CHAR,
  uwinspfreq NUMBER(2),
  uwlastinsp DATE,
  uwnextdate DATE,
  fcinspreq CHAR,
  fcinspdone CHAR,
  fcinspfreq NUMBER(2),
  fclastinsp DATE,
  fcnextdate DATE,
  osinspreq CHAR,
  osinspdone CHAR,
  osinspfreq NUMBER(2),
  oslastinsp DATE,
  osnextdate DATE,
  ietrigger CHAR,
  apprdate DATE,
  railrating CHAR,
  transratin CHAR,
  arailratin CHAR,
  aendrating CHAR,
  oppostcl CHAR,
  deckgeom CHAR,
  underclr CHAR,
  wateradeq CHAR,
  pierprot CHAR,
  scourcrit CHAR,
  appralign CHAR,
  dkrating CHAR,
  suprating CHAR,
  subrating CHAR,
  chanrating CHAR,
  culvrating CHAR,
  strrating CHAR,
  nbi_rating CHAR,
  suff_rate NUMBER(4,1),
  suff_prefx CHAR,
  insptype CHAR NOT NULL,
  inspstat CHAR,
  deckdistr FLOAT,
  bitrigger CHAR,
  recworkflg CHAR,
  createdatetime DATE,
  createuserkey VARCHAR2(4 BYTE),
  modtime DATE,
  userkey VARCHAR2(4 BYTE),
  docrefkey VARCHAR2(255 BYTE),
  notes VARCHAR2(2000 BYTE),
  elemconvert CHAR
);