CREATE TABLE pontis.vc_roadway (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  on_under VARCHAR2(2 BYTE) NOT NULL,
  kind_hwy CHAR,
  levl_srvc CHAR,
  routenum VARCHAR2(5 BYTE),
  dirsuffix CHAR,
  roadway_name VARCHAR2(30 BYTE),
  crit_feat CHAR,
  kmpost FLOAT,
  bypasslen FLOAT,
  tollfac CHAR,
  defhwy CHAR,
  trucknet CHAR,
  lanes NUMBER(2),
  funcclass VARCHAR2(2 BYTE),
  adttotal NUMBER(8),
  adtyear NUMBER(4),
  trafficdir CHAR,
  truckpct NUMBER(2),
  adtfuture NUMBER(8),
  adtfutyear NUMBER(4),
  road_speed NUMBER(4),
  det_speed NUMBER(4),
  school_bus CHAR,
  transit_rt CHAR,
  crit_trav CHAR,
  num_median CHAR,
  ten_yr_cnt NUMBER(5),
  acc_rate NUMBER(6),
  acc_risk NUMBER(10,9),
  vclrinv FLOAT,
  hclrinv FLOAT,
  aroadwidth FLOAT,
  roadwidth FLOAT,
  rkey VARCHAR2(2 BYTE),
  rinspdone CHAR,
  nhs_ind CHAR,
  userrwkey1 VARCHAR2(30 BYTE),
  userrwkey2 VARCHAR2(30 BYTE),
  userrwkey3 VARCHAR2(30 BYTE),
  userrwkey4 VARCHAR2(30 BYTE),
  userrwkey5 VARCHAR2(30 BYTE),
  nbi_rw_flag CHAR,
  acc_count NUMBER(6,2),
  rtrigger CHAR,
  fedlandhwy CHAR,
  adtclass VARCHAR2(2 BYTE),
  onbasenet CHAR,
  lrsinvrt VARCHAR2(10 BYTE),
  subrtnum VARCHAR2(2 BYTE),
  createdatetime DATE,
  createuserkey VARCHAR2(4 BYTE),
  userkey VARCHAR2(4 BYTE),
  modtime DATE,
  docrefkey VARCHAR2(255 BYTE),
  notes VARCHAR2(2000 BYTE)
);