CREATE TABLE pontis.vc_userrway (
  brkey VARCHAR2(15 BYTE) NOT NULL,
  on_under VARCHAR2(2 BYTE) NOT NULL,
  clr_route VARCHAR2(8 BYTE),
  route_num VARCHAR2(5 BYTE),
  route_prefix CHAR,
  route_suffix CHAR,
  route_unique_id CHAR,
  maint_rte_num VARCHAR2(5 BYTE),
  maint_rte_prefix CHAR,
  maint_rte_suffix CHAR,
  maint_rte_id CHAR,
  road_cross_name VARCHAR2(50 BYTE),
  feat_cross_type VARCHAR2(3 BYTE),
  feat_desc_type VARCHAR2(3 BYTE),
  aroadwidth_far FLOAT,
  aroadwidth_near FLOAT,
  trans_lanes FLOAT,
  chan_prot_left VARCHAR2(4 BYTE),
  chan_prot_right VARCHAR2(4 BYTE),
  berm_prot VARCHAR2(4 BYTE),
  hclr_n FLOAT,
  hclr_e FLOAT,
  hclr_s FLOAT,
  hclr_w FLOAT,
  vclrinv_n FLOAT,
  vclrinv_e FLOAT,
  vclrinv_s FLOAT,
  vclrinv_w FLOAT,
  hclrult_n FLOAT,
  hclrult_e FLOAT,
  hclrult_s FLOAT,
  hclrult_w FLOAT,
  hclrurt_n FLOAT,
  hclrurt_e FLOAT,
  hclrurt_s FLOAT,
  hclrurt_w FLOAT,
  vclr_n FLOAT,
  ln1_vclr_n FLOAT,
  ln2_vclr_n FLOAT,
  ln3_vclr_n FLOAT,
  ln4_vclr_n FLOAT,
  ln5_vclr_n FLOAT,
  ln6_vclr_n FLOAT,
  ln7_vclr_n FLOAT,
  ln8_vclr_n FLOAT,
  vclr_e FLOAT,
  ln1_vclr_e FLOAT,
  ln2_vclr_e FLOAT,
  ln3_vclr_e FLOAT,
  ln4_vclr_e FLOAT,
  ln5_vclr_e FLOAT,
  ln6_vclr_e FLOAT,
  ln7_vclr_e FLOAT,
  ln8_vclr_e FLOAT,
  vclr_s FLOAT,
  ln1_vclr_s FLOAT,
  ln2_vclr_s FLOAT,
  ln3_vclr_s FLOAT,
  ln4_vclr_s FLOAT,
  ln5_vclr_s FLOAT,
  ln6_vclr_s FLOAT,
  ln7_vclr_s FLOAT,
  ln8_vclr_s FLOAT,
  vclr_w FLOAT,
  ln1_vclr_w FLOAT,
  ln2_vclr_w FLOAT,
  ln3_vclr_w FLOAT,
  ln4_vclr_w FLOAT,
  ln5_vclr_w FLOAT,
  ln6_vclr_w FLOAT,
  ln7_vclr_w FLOAT,
  ln8_vclr_w FLOAT,
  totlanes FLOAT,
  vclr_n_sign FLOAT,
  vclr_s_sign FLOAT,
  vclr_e_sign FLOAT,
  vclr_w_sign FLOAT,
  toll_kdot CHAR,
  adt_expan_fctr FLOAT,
  vc_date DATE,
  createdatetime DATE,
  createuserkey VARCHAR2(4 BYTE),
  modtime DATE,
  userkey VARCHAR2(4 BYTE),
  notes VARCHAR2(2000 BYTE)
);