CREATE OR REPLACE TRIGGER pontis.TAUR_UBRDG_POSTING_NBI70
	AFTER UPDATE OF ORLOAD_ADJ_HS,ORLOAD_LFD_HS,ORLOAD_WSD_HS
 ON pontis.USERBRDG

  FOR EACH ROW

  




DECLARE V_BRIDGE_POSTING BRIDGE.POSTING%TYPE;
    TEMPCALC  USERBRDG.ORLOAD_ADJ_HS%TYPE;
    P_CALC  USERBRDG.ORLOAD_ADJ_HS%TYPE;
    RETVAL CHAR(1);
BEGIN


IF (:NEW.ORLOAD_ADJ_HS > 0) THEN
   TEMPCALC := :NEW.ORLOAD_ADJ_HS;
   P_CALC := round((20.41 - TEMPCALC)*100/20.41,2);
ELSIF (:NEW.ORLOAD_ADJ_HS IS NULL AND :NEW.ORLOAD_LFD_HS  > 0) THEN
    TEMPCALC := :NEW.ORLOAD_LFD_HS;
    P_CALC := ROUND((20.41 - TEMPCALC)*100/20.41);
ELSE TEMPCALC := :NEW.ORLOAD_WSD_HS;
    P_CALC := ROUND((20.41 - TEMPCALC)*100/20.41);
 
end if;
IF p_CALC < 0 THEN
   RETVAL :='5';
END IF;
IF P_CALC > 0.0 and P_CALC <= 10.0 THEN
     RETVAL := '4';
END IF;
IF P_CALC > 10.0  and P_CALC <= 20.0 THEN
     RETVAL := '3';
END IF;
IF P_CALC = 20.0  and P_CALC <= 30.0 THEN
   RETVAL := '2';
END IF;
IF P_CALC > 30.0  and P_CALC <= 39.9 THEN
     RETVAL := '1';
END IF;
IF P_CALC > 39.9 AND P_CALC <= 100.0 THEN
   RETVAL:= '0';
END IF;
   
 
  V_BRIDGE_POSTING := RETVAL;

  
-- Now, Put This POSTING into the bridge.posting field...
UPDATE BRIDGE
  SET POSTING = V_BRIDGE_POSTING
  WHERE
  BRIDGE.BRKEY = :OLD.BRKEY;
  
UPDATE BRIDGE
SET USERKEY14 = TO_CHAR(P_CALC)
WHERE BRIDGE.BRKEY = :OLD.BRKEY;

END TAUR_UBRDG_POSTING_NBI70;
/