CREATE OR REPLACE TRIGGER pontis.TAUR_USERSTRUNIT_ITEM43

	AFTER UPDATE OF UNIT_MATERIAL, UNIT_TYPE, SUPER_DESIGN_TY ON pontis.USERSTRUNIT
	FOR EACH ROW
	




DECLARE V_StrUnitType STRUCTURE_UNIT.STRUNITTYPE%TYPE;
        V_UNIT_TYPE_TEMP_CODE USERSTRUNIT.UNIT_TYPE%TYPE;
		    V_UNIT_MATERIAL_TEMP_CODE USERSTRUNIT.UNIT_MATERIAL%TYPE;
        V_SUPER_DESIGN_TY USERSTRUNIT.SUPER_DESIGN_TY%TYPE;
        ITEM_43 BRIDGE.USERKEY15%TYPE;
        V_NBI_RESULT_CODE BRIDGE.USERKEY15%TYPE;
BEGIN

SELECT STRUNITTYPE INTO V_StrUnitType FROM STRUCTURE_UNIT
 WHERE
  STRUCTURE_UNIT.BRKEY = :OLD.BRKEY
   AND STRUCTURE_UNIT.STRUNITKEY = :OLD.STRUNITKEY;
   
-- Check to See if this is the Main Unit :

If V_StrUnitType = '1' Then

-- It IS the Main Structure Unit. Designate The Unit_MATERIAL for this Unit
-- to be the MATERIALMAIN for the ENTIRE Structure (for NBI):

-- Look up the NBI code for the KDOT field
V_UNIT_MATERIAL_TEMP_CODE := ksbms_pontis.get_nbicode_from_NBILookup( 'USERSTRUNIT', 'UNIT_MATERIAL', :new.UNIT_MATERIAL );
V_UNIT_TYPE_TEMP_CODE := ksbms_pontis.get_nbicode_from_NBILookup ('USERSTRUNIT','UNIT_TYPE', :NEW.UNIT_TYPE );

If V_UNIT_MATERIAL_TEMP_CODE IN ('1','3','5') AND (:NEW.SUPER_DESIGN_TY IN ('2','3')  ) then
   V_UNIT_MATERIAL_TEMP_CODE := TO_NUMBER(V_UNIT_MATERIAL_TEMP_CODE)+1;
      
END IF;

if (V_UNIT_MATERIAL_TEMP_CODE = '3' AND V_UNIT_TYPE_TEMP_CODE = '4' )THEN
   ITEM_43 := '308';
  ELSIF V_UNIT_TYPE_TEMP_CODE = '19' AND (:NEW.SUPER_DESIGN_TY <> '0') THEN
    ITEM_43 := TO_NUMBER(TO_CHAR(V_UNIT_MATERIAL_TEMP_CODE)||'07');
  ELSE
    ITEM_43 := TO_CHAR(V_UNIT_MATERIAL_TEMP_CODE)||ltrim(V_UNIT_TYPE_TEMP_CODE,'00');
END IF;

UPDATE BRIDGE
	SET MATERIALMAIN = SUBSTR(ITEM_43,1,1)
	WHERE
	BRIDGE.BRKEY = :OLD.BRKEY;

UPDATE BRIDGE
SET DESIGNMAIN = LTRIM(SUBSTR(ITEM_43,2,2),'0')
WHERE 
BRIDGE.BRKEY = :OLD.BRKEY;

END IF;
-- Note : If this is NOT the Main Unit, then the MATERIALMAIN is not Assigned!

END TAUR_USERSTRUNIT_ITEM_43;
/