CREATE OR REPLACE TRIGGER pontis.TAUR_UINSP_OPPOSTCL
	AFTER UPDATE OF OPPOSTCL_KDOT ON pontis.USERINSP
	FOR EACH ROW
	



DECLARE	v_nbi_result_code INSPEVNT.OPPOSTCL%TYPE;
BEGIN

-- Look up the NBI code for the KDOT field 
v_nbi_result_code := get_nbicode_from_NBILookup( 'USERINSP', 'OPPOSTCL_KDOT', :new.OPPOSTCL_KDOT );

UPDATE INSPEVNT
	SET OPPOSTCL = V_NBI_RESULT_CODE
	WHERE
	INSPEVNT.BRKEY = :OLD.BRKEY AND
	INSPEVNT.INSPKEY = :OLD.INSPKEY;
END;
/