CREATE OR REPLACE TRIGGER pontis.TAUR_USERSTRUNIT_NUMMAINSPAN
	AFTER UPDATE OF NUM_SPANS_GRP_1, NUM_SPANS_GRP_2,NUM_SPANS_GRP_3,NUM_SPANS_GRP_4, NUM_SPANS_GRP_5, NUM_SPANS_GRP_6,NUM_SPANS_GRP_7,NUM_SPANS_GRP_8, NUM_SPANS_GRP_9, NUM_SPANS_GRP_10 ON pontis.USERSTRUNIT
	FOR EACH ROW
	




DECLARE V_STRUNITTYPE STRUCTURE_UNIT.STRUNITTYPE%TYPE;
	        V_MAINSPANS_NBI BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_1 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_2 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_3 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_4 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_5 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_6 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_7 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_8 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_9 BRIDGE.MAINSPANS%TYPE;
	        TMP_NUM_SPANS_GRP_10 BRIDGE.MAINSPANS%TYPE;
BEGIN

SELECT STRUNITTYPE INTO V_StrUnitType FROM STRUCTURE_UNIT
 WHERE
  STRUCTURE_UNIT.BRKEY = :OLD.BRKEY
   AND STRUCTURE_UNIT.STRUNITKEY = :OLD.STRUNITKEY;



-- Check to See if this is the Main Unit :
If V_StrUnitType = '1' Then

  If (:NEW.NUM_SPANS_GRP_1 IS NULL OR :NEW.NUM_SPANS_GRP_1 < 0 ) then
	TMP_NUM_SPANS_GRP_1 := 0;
  else
	TMP_NUM_SPANS_GRP_1 := :NEW.NUM_SPANS_GRP_1;
  end if;

  If (:NEW.NUM_SPANS_GRP_2 IS NULL OR :NEW.NUM_SPANS_GRP_2 < 0 ) then
	TMP_NUM_SPANS_GRP_2 := 0;
  else
	TMP_NUM_SPANS_GRP_2 := :NEW.NUM_SPANS_GRP_2;
  end if;

  If (:NEW.NUM_SPANS_GRP_3 IS NULL OR :NEW.NUM_SPANS_GRP_3 < 0 ) then
	TMP_NUM_SPANS_GRP_3 := 0;
  else
	TMP_NUM_SPANS_GRP_3 := :NEW.NUM_SPANS_GRP_3;
  end if;

  If (:NEW.NUM_SPANS_GRP_4 IS NULL OR :NEW.NUM_SPANS_GRP_4 < 0 ) then
	TMP_NUM_SPANS_GRP_4 := 0;
  else
	TMP_NUM_SPANS_GRP_4 := :NEW.NUM_SPANS_GRP_4;
  end if;

  If (:NEW.NUM_SPANS_GRP_5 IS NULL OR :NEW.NUM_SPANS_GRP_5 < 0 ) then
	TMP_NUM_SPANS_GRP_5 := 0;
  else
	TMP_NUM_SPANS_GRP_5 := :NEW.NUM_SPANS_GRP_5;
  end if;

  If (:NEW.NUM_SPANS_GRP_6 IS NULL OR :NEW.NUM_SPANS_GRP_6 < 0 ) then
	TMP_NUM_SPANS_GRP_6 := 0;
  else
	TMP_NUM_SPANS_GRP_6 := :NEW.NUM_SPANS_GRP_6;
  end if;

  If (:NEW.NUM_SPANS_GRP_7 IS NULL OR :NEW.NUM_SPANS_GRP_7 < 0 ) then
	TMP_NUM_SPANS_GRP_7 := 0;
  else
	TMP_NUM_SPANS_GRP_7 := :NEW.NUM_SPANS_GRP_7;
  end if;

  If (:NEW.NUM_SPANS_GRP_8 IS NULL OR :NEW.NUM_SPANS_GRP_8 < 0 ) then
	TMP_NUM_SPANS_GRP_8 := 0;
  else
	TMP_NUM_SPANS_GRP_8 := :NEW.NUM_SPANS_GRP_8;
  end if;

  If (:NEW.NUM_SPANS_GRP_9 IS NULL OR :NEW.NUM_SPANS_GRP_9 < 0 ) then
	TMP_NUM_SPANS_GRP_9 := 0;
  else
	TMP_NUM_SPANS_GRP_9 := :NEW.NUM_SPANS_GRP_9;
  end if;

  If (:NEW.NUM_SPANS_GRP_10 IS NULL OR :NEW.NUM_SPANS_GRP_10 < 0 ) then
	TMP_NUM_SPANS_GRP_10 := 0;
  else
	TMP_NUM_SPANS_GRP_10 := :NEW.NUM_SPANS_GRP_10;
  end if;


V_MAINSPANS_NBI := (TMP_NUM_SPANS_GRP_1+TMP_NUM_SPANS_GRP_2+TMP_NUM_SPANS_GRP_3+TMP_NUM_SPANS_GRP_4+TMP_NUM_SPANS_GRP_5+TMP_NUM_SPANS_GRP_6+TMP_NUM_SPANS_GRP_7+TMP_NUM_SPANS_GRP_8+TMP_NUM_SPANS_GRP_9+TMP_NUM_SPANS_GRP_10);


-- Now, Put This Sum of Main Spans into the Pontis BRIDGE Table;
UPDATE bridge
	SET MAINSPANS = V_MAINSPANS_NBI
	WHERE
	BRIDGE.BRKEY = :OLD.BRKEY;
end if;

END TAUR_USERSTRUNIT_NUMMAINSPAN;
/