CREATE OR REPLACE TRIGGER pontis.TAUR_UINSP_INSPECTOR
  AFTER UPDATE OF R_INSPNAME_1 ON pontis.USERINSP
  FOR EACH ROW
  


  WHEN ( nvl( new.R_INSPNAME_1,'<MISSING>') <>  nvl( OLD.R_INSPNAME_1,'<MISSING>' ) ) BEGIN


UPDATE INSPEVNT
  SET INSPUSRKEY = :NEW.R_INSPNAME_1
  WHERE
  INSPEVNT.BRKEY = :OLD.BRKEY AND
  INSPEVNT.INSPKEY = :OLD.INSPKEY;
END;
/